<div class="row">
	<!--news -->
	<div id="sidebar" class="8u 12u(mobile) homepage">
		<section>					
			<header>
				<h2 style="border-bottom: 2px #d0d0d0 solid; width:25%"><a href="javascript:void(0)">最新消息</a></h2>
			</header>
			<ul class="divided">
				<?php 
					foreach($data as $k0 => $v0) {
						echo '<li><article class="box excerpt">
							<header>
								<span class="date">'.date('Y-m-d', strtotime($v0['date'])).'</span>
								<h3><a onclick="show_news(\''.date('Y-m-d', strtotime($v0['date'])).'\', \''.$v0['title'].'\', \''.$v0['content'].'\')" href="javascript:void(0)">'.$v0['title'].'</a></h3>
							</header>
							<p>'.$v0['content'].'</p>
						</article>
						</li>';
					}
				?>
			</ul>
		</section>
		
		<!-- 修繕項目 -->
		<section>
			<header>
				<h2 style="border-bottom: 2px #d0d0d0 solid; width:25%;margin-top:2em;"><a href="#">修繕項目</a></h2>
			</header>
			<ul class="divided">
				<li>
					<article class="box excerpt">
						<header>
							<span class="date"><h1>室內裝潢</h1></span>
							<h3><a href="#"></a></h3>
						</header>
						<p class="index_item">舉凡室內裝潢、室內裝修、房屋增建修改、拆除隔間、舊屋整修、室內裝修翻新、室內格局重整、浴室整修、廚房改造、加蓋頂樓、屋頂翻新加高、天花板、油漆粉刷、大小工作不拘、免費至府估價、歡迎比價、二十多年房屋修繕、房屋增建、舊屋翻修、舊屋翻新、舊屋整修、房屋整修、房屋整建、房屋翻修的豐富經驗、服務大台南縣市、油漆粉刷、室內裝潢、室內裝修、防水抓漏、房屋增建修改、披土修補、水泥漆、塑膠漆、房屋隔間、服務有口碑的二十多年經驗。</p>
					</article>
					<br>
					<article class="box excerpt">
						<header>
							<span class="date"><h1>防水施做</h1></span>
							<h3><a href="#"></a></h3>
						</header>
						<p class="index_item">
							1.先將欲施作之面積全數拆除,直到看見最底層原始的RC結
							構層,再將細砂石掃乾淨,爾後於烈陽下曝晒,讓滲透入RC結構層內的水份能完全蒸發。<br>
							2.【第一層】察視RC結構層內的水份是否已完全蒸發出來,如果已完全蒸發出來,就立即將[頂樓防水專用的彈性水泥]加上獨家配方,塗抹於RC結構層上,按標準的塗抹厚度,使其平均佈滿於RC結構層上,並且上轉至女兒牆約30~40cm處,以確保轉角處不會滲水。<br>
							3.【第二層】待次日,見第一層已經完全乾燥後,將防止底層
							因過大的地震而產生龜裂用的防裂網平鋪於第一層上面,立即再將[頂樓防水專用的彈性水泥] 加上獨家配方,塗抹於全部的施作面積,一樣按照標準的厚度,塗抹於防裂網上面, 並且上轉至女兒牆約30~40cm處,以確保轉角處不會滲水,亦可強化其防水功能。<br>
							4.【第三層】待次日,仔細察看是否施作面積已經完全乾燥,倘若已經完全乾燥,便可施作混凝土的瀉水坡度,必須確實抓出高效率的瀉水速度,使落下來的雨水能快速的
							流至排水孔內,不會淤積在樓面上。施作混凝土的瀉水坡度
							時,其表面乾燥後,須呈現光滑細緻的表面,並且必須每天進行俗稱（養水）的程序,以確保水泥乾燥後不會產生細小的龜裂痕跡,亦不容易起沙,能使上層的防水底材緊密的附著於水泥乾燥後的表面。<br>
							5.【第四層】大約經過5~7天後方可施作PU防水的底材。
						</p>
					</article>
					<br>
					<article class="box excerpt">
						<header>
							<span class="date"><h1>壁磚</h1></span>
							<h3><a href="#"></a></h3>
						</header>
						<p class="index_item">
						(1) 應採用硬底砂漿工法鋪貼。
						(2) 首先應檢查底層砂漿或混凝土面不得有乳沫，龜裂等現象，若有油質，灰塵應先行用清水洗淨。 
						(3) 粘貼不同規格磁磚，應先行規劃平面圖。
						(4) 以銼子定出垂直線，並以4.5×4.5或2.5×2.5㎝馬賽克定出垂直面標記。
						(5) 打底前，舊壁面以清水保濕，並以水泥漿刷抹壁面，促使打底砂漿更牢固。
						(6) 以木鏝刀在牆面打底，徹底抹平垂直面，並力求紮實平整。(水泥砂比例1:3) 再以防水彈性泥施作防水層。
						(7) 待施作面確定凝固後再行放樣，放樣時應注意其配件(馬賽克,腰帶…等)之厚度以利判斷施工技術，並於放樣前務必檢
							 查丈量現品之尺寸，以求放樣準確度。</p>
					</article>

				</li>

				</li>
			</ul>
		</section>
		

	</div>
	
<!-- Content -->
	<div id="content" class="4u 12u(mobile) homepage" >

		<!-- Post -->
			<article class="box post">
				<header>
					<h2 class="right_slider" style="border-bottom: 2px #d0d0d0 solid;"><a href="#">修繕成果</a></h2>
				</header>
				<h4>居家修繕成果展示1</h4>
				<a href="#" class="image featured"><img src="<?php echo URL_IMG.'1.jpg' ?>" /></a>
				

			</article>

			<article class="box post">
				<h4>居家修繕成果展示2</h4>
				<a href="#" class="image featured"><img src="<?php echo URL_IMG.'2.jpg' ?>" /></a>
				

			</article>

			<article class="box post">
				<h4>居家修繕成果展示3</h4>
				<a href="#" class="image featured"><img src="<?php echo URL_IMG.'3.jpg' ?>" /></a>
				

			</article>

			<article class="box post">
				<h4>居家修繕成果展示4</h4>
				<a href="#" class="image featured"><img src="<?php echo URL_IMG.'4.jpg' ?>" /></a>
				

			</article>

			<article class="box post">
				<h4>居家修繕成果展示5</h4>
				<a href="#" class="image featured"><img src="<?php echo URL_IMG.'5.jpg'?>" /></a>
				

			</article>


	</div>
</div>
<script>
function show_news(date, title, content) {
	var box = new jBox('Modal', {
			closeButton: 'title',
			delayOpen: 300,
			maxWidth: 600,
			minWidth: 100,
			title: date + '<div style="letter-spacing: 1px;font-weight:bold">'+title+'</div>',
	}).setContent('<div style="color:#757575; font-size:16px;line-height:30px;letter-spacing: 2px;padding:1em;">' + content + '</div>').open();
}
</script>

