<!-- Sidebar -->
	<div id="sidebar" class="4u 12u(mobile)">
		
		<!-- 最新消息 -->
			<section>					
				<header>
					<h2 style="border-bottom: 2px #d0d0d0 solid; width:25%"><a href="#">最新消息</a></h2>
				</header>
				<ul class="divided">
					<li>

						<!-- Excerpt -->
							<article class="box excerpt">
								<header>
									<span class="date">2016-02-24</span>
									<h3><a href="#">新誠居家修繕工程 網站上線服務了!!</a></h3>
								</header>
								<p>新誠居家修繕工程的官方網站正式上線服務</p>
							</article>

					</li>
					<li>

							<article class="box excerpt">
								<header>
									<span class="date">2016-02-24</span>
									<h3><a href="#">新誠居家修繕工程 網站上線服務了!!</a></h3>
								</header>
								<p>新誠居家修繕工程的官方網站正式上線服務</p>
							</article>

					</li>
					<li>

							<article class="box excerpt">
								<header>
									<span class="date">2016-02-24</span>
									<h3><a href="#">新誠居家修繕工程 網站上線服務了!!</a></h3>
								</header>
								<p>新誠居家修繕工程的官方網站正式上線服務</p>
							</article>

					</li>
					<li>

							<article class="box excerpt">
								<header>
									<span class="date">2016-02-24</span>
									<h3><a href="#">新誠居家修繕工程 網站上線服務了!!</a></h3>
								</header>
								<p>新誠居家修繕工程的官方網站正式上線服務</p>
							</article>

					</li>
					<li>

							<article class="box excerpt">
								<header>
									<span class="date">2016-02-24</span>
									<h3><a href="#">新誠居家修繕工程 網站上線服務了!!</a></h3>
								</header>
								<p>新誠居家修繕工程的官方網站正式上線服務</p>
							</article>

					</li>
				</ul>
			</section>
		
		<!-- 修繕項目 -->
		
			<section>
				<header>
					<h2 style="border-bottom: 2px #d0d0d0 solid; width:25%"><a href="#">修繕項目</a></h2>
				</header>
				<ul class="divided">
					<li>
							<article class="box excerpt">
								<header>
									<span class="date">室內裝潢</span>
									<h3><a href="#"></a></h3>
								</header>
								<p style="font-size:0.6em">舉凡室內裝潢、室內裝修、房屋增建修改、拆除隔間、舊屋整修、室內裝修翻新、室內格局重整、浴室整修、廚房改造、加蓋頂樓、屋頂翻新加高、天花板、油漆粉刷、大小工作不拘、免費至府估價、歡迎比價、二十多年房屋修繕、房屋增建、舊屋翻修、舊屋翻新、舊屋整修、房屋整修、房屋整建、房屋翻修的豐富經驗、服務大台南縣市、油漆粉刷、室內裝潢、室內裝修、防水抓漏、房屋增建修改、披土修補、水泥漆、塑膠漆、房屋隔間、服務有口碑的二十多年經驗。</p>
							</article>

					</li>

					</li>
				</ul>
			</section>
		

	</div>
	
<!-- Content -->
	<div id="content" class="8u 12u(mobile)">

		<!-- Post -->
			<article class="box post">
				<header>
					<h2  style="border-bottom: 2px #d0d0d0 solid; width:44%"><a href="#">修繕成果</a></h2>
				</header>
				<h4>居家修繕成果展示1</h4>
				<a href="#" class="image featured"><img src="images/pic04.jpg" alt="" /></a>
				

			</article>

			<article class="box post">
				<h4>居家修繕成果展示2</h4>
				<a href="#" class="image featured"><img src="images/7.jpg" alt="" /></a>
				

			</article>

			<article class="box post">
				<h4>居家修繕成果展示3</h4>
				<a href="#" class="image featured"><img src="images/39.jpg" alt="" /></a>
				

			</article>

			<article class="box post">
				<h4>居家修繕成果展示4</h4>
				<a href="#" class="image featured"><img src="images/39.jpg" alt="" /></a>
				

			</article>

			<article class="box post">
				<h4>居家修繕成果展示5</h4>
				<a href="#" class="image featured"><img src="images/39.jpg" alt="" /></a>
				

			</article>


	</div>
