<div class="row">
	<!--news -->
	<div id="sidebar" class="8u 12u(mobile) homepage">
		<section>					
			<header>
				<h2 style="border-bottom: 2px #d0d0d0 solid; width:25%"><a href="javascript:void(0)">最新消息</a></h2>
			</header>
			<ul class="divided">
				<?php 
					foreach($a_news as $k0 => $v0) {
						$icon = (date('Y-m-d', strtotime($v0['release'])) >=  date('Y-m-d', strtotime('-7 days'))) ? '&nbsp;&nbsp;<img width="32" height="10" src="'.URL_IMG.'gif_new.gif'.'">' : null ;
						echo '<li><article class="box excerpt">
							<header>
								<span class="date">'.date('Y-m-d', strtotime($v0['release'])).$icon.'</span>
								<h3>
									<a onclick="show_news(\''.date('Y-m-d', strtotime($v0['release'])).'\', \''.$v0['title'].'\', \''.$v0['content'].'\')" href="javascript:void(0)">'.$v0['title'].'</a>
								</h3>
							</header>
							<p>'.$v0['content'].'</p>
						</article>
						</li>';
					}
				?>
			</ul>
		</section>
		<!-- 修繕項目 -->
		<section>
			<header>
				<h2 style="border-bottom: 2px #d0d0d0 solid; width:25%;margin-top:2em;"><a href="javascript:void(0)">修繕項目</a></h2>
			</header>
			<ul class="divided">
				<li>
					<?php 
						foreach ($a_ad as $k0 => $v0) {
							echo '<article class="box excerpt">
									<header>
										<span class="date"><h1>'.$v0['name'].'</h1></span>
									</header>
									'.$v0['content'].'
								</article>
								<br>';
						}
					?>
				</li>
			</ul>
		</section>
	</div>
	
<!-- Content -->
	<div id="content" class="4u 12u(mobile) homepage" >
		<?php 
			foreach ($a_product as $k0 => $v0) {
				$_this_head = ($k0==0) ? '<h2 class="right_slider" style="border-bottom: 2px #d0d0d0 solid;"><a href="javascript:void(0);">修繕成果</a></h2>' : null;
				if(is_file(PATH_FILES.'product/'.$v0['product_id'].'/'.$v0['cover'])) image_remake(PATH_FILES.'product/'.$v0['product_id'].'/'.$v0['cover'], 'jpg', 371, 248, 'w');
				echo '<article class="box post">
						<header>'.$_this_head.'</header>
						<h4>'.$v0['name'].'</h4>
						<a href="'.url('detail', 'index', ['id'=>$v0['product_id']]).'" class="image featured"><img src="'.URL_FILES.'product/'.$v0['product_id'].'/'.sinechat_Thumbnail($v0['cover'], 371, 248).'" /></a>
					</article>';
			}

		?>
	</div>
</div>

<script>
$(document).on('ready', function(){
	$('article.excerpt').children('p').addClass('index_item');
})

function show_news(date, title, content) {
	var box = new jBox('Modal', {
			closeButton: 'title',
			delayOpen: 300,
			maxWidth: 600,
			minWidth: 100,
			title: date + '<div style="letter-spacing: 1px;font-weight:bold">'+title+'</div>',
	}).setContent('<div style="color:#757575; font-size:16px;line-height:30px;letter-spacing: 2px;padding:1em;">' + content + '</div>').open();
}
</script>

