<section class="content-header">
	<div class="box-body"><h2>關於新誠</h2></div>
	<h1>				
		<small><p class="text-light-blue">(建議上傳圖片格式: PNG / JPEG / JPG)</p></small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="<?php echo url('admin', 'index') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">關於新誠</li>
	</ol>
</section>
<section class="content">
	<div class="box">
		<div class="box-body">
			<form method="post">
				<textarea rows="10" cols="50" id="about_value" name="about_value" class="ckeditor"><?php echo (!empty($data['value'])) ? $data['value'] : null; ?></textarea>
				<script type="text/javascript">CKEDITOR.replace('about_value',
				{toolbar : 'Full'});
				</script><br>
				<a class="btn btn-app " id="save">
					<i class="fa fa-save"></i> Save
				</a>
			</form>
		</div>
		<div class="box-footer">
			
		</div>
	</div>
</section>
<script>
$(function () {
	$('#save').on('click', function(){
		$.post('<?php echo url('admin', 'about') ?>' , {
			value : CKEDITOR.instances['about_value'].getData(),
		},function(r){
			r = $.parseJSON(r);
			if(r.result == 1) {
				_jbox(r, 'success');
			}else{
				_jbox(r, 'error');			
			}
		});
		
	});

});
</script>