<section class="content-header">
	<div class="box-body"><h2>聯絡我們 - 內容</h2></div>
	<h1>				
		<small><p class="text-light-blue"></p></small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="<?php echo url('admin', 'index') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
		<li><a href="<?php echo url('admin', 'servicearea') ?>">聯絡我們 - 內容</a></li>
		<li class="active">詳情</li>
	</ol>
</section>
<section class="content">
	<div class="box">
		<div class="box-body">
			<div class="row">
				<div class="col-md-10">
					<div class="box-body box-solid">
						<div class="box-header with-border">
							<i class="fa fa-file-text-o"></i>
							<h3 class="box-title"> <?php echo  '查看聯絡內容 ： '.$data['name'] ?> </h3>
						</div>
						<div class="box-body">
							<dl class="dl-horizontal" style="font-size:1.1em;">
								<dt>編號:</dt>
									<dd><?php echo '#'.$data['contact_id'] ?></dd>
								<dt>Name:</dt>
									<dd><?php echo $data['name'] ?></dd>
								<dt>Tel:</dt>
									<dd><?php echo $data['tel'] ?></dd>
								<dt>Email:</dt>
									<dd><?php echo $data['email'] ?></dd>
								<dt>Gender:</dt>
									<dd><?php echo $data['gender'] ?></dd>
								<dt>Memo:</dt>
									<dd><?php echo $data['memo'] ?></dd>
								<dt>Read Time:</dt>
									<dd><?php echo $data['read_time'] ?></dd>
								<dt>聯繫時間:</dt>
								<dd><?php echo $data['inserttime'] ?></dd>
							</dl>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<a class="btn btn-app" href="<?php echo url('admin', 'contact') ?>">
	<i class="fa fa-angle-double-left"></i> 上一頁
</a>
<a class="btn btn-app " id="save">
	<i class="fa fa-folder-open-o"></i> 封存(Save)
</a>
<a class="btn btn-app" id="delete">
	<i class="fa fa-trash-o"></i> 刪除(Delete)
</a>

<script>

$(function () {

	$('#save').on('click', function(){
			var seqence = $('input[name=seqence]');

			if (!/^\d+$/.test(seqence.val())) {
				seqence.val(/^\d+/.exec(seqence.val()));
				r = {'message': '排序須輸入正整數。'};
				site_jBox(r, 'error');
			}else{
				$.post('<?php echo url('admin', 'contact/edit') ?>' , {
					act : '',
					contact_id : '<?php echo $data['contact_id'] ?>',
					name : $('input[name="name"]').val(),
					seqence : seqence.val(),
					status : $('input[name="status"]:checked').val(),
				},function(r){
					r = $.parseJSON(r);
					if(r.result == 1) {
						_jbox(r, 'success');
					}else{
						_jbox(r, 'error');			
					}
				});
			}
	});

	$('#delete').on('click', function(){
		var Confirm_box = new jBox('Confirm', {
				cancelButton: '否',
				confirmButton: '是',
				title : '<span style="display: inline-block;height: 100%;vertical-align: middle;"><i style="color:#3C8DBC;font-size:2em ;" class="fa fa-info-circle"></span>',
				confirm: function() {
					$.post('' , {
						servicearea_id : '',
					},function(r){
						r = $.parseJSON(r);
						if(r.result == 1) {
							_jbox(r, 'success');
						}else{
							_jbox(r, 'error');			
						}
					});
				},
				onCloseComplete: function() {	
					Confirm_box.destroy();
				}
			}).setContent(
				'<div>' +
				'<p>確定要刪除此筆資料嗎?</p>' +
				'</div>'
			).open();
	});
	
});

</script>