<div class="row">
	<div class="12u 12u(mobile)">
		<div class="bc_container">
			<ul id="bc1" class="breadcrumb">
				<li><a href="<?php echo url(); ?>"><i class="fa fa-home"></i> Home</a></li>
				<li><a href="<?php echo url('product', 'index'); ?>">成果展示</a></li>
				<li class="active"><?php echo $product['name'] ?></li>
			</ul>
		</div>
	</div>

	<!-- Other -->
	<div id="content" class="3u 12u(mobile) important(mobile) content_other" >
		<section>
			<div>
				<article class="box post">
					<header><h2>&nbsp;<strong></strong> </h2></header>
				</article>
			</div>
			<header>
				<h2 style="border-bottom: 2px #d0d0d0 solid; margin-top:2em;width:55%;">其他作品</h2>
			</header>
			<ul class="divided">
				<li style="width:90%">
					<?php 
						if(!empty($other) && is_array($other)) {
							foreach($other as $k0 => $v0) {
								if(is_file(PATH_FILES.'product/'.$v0['product_id'].'/'.$v0['cover'])) image_reformat(PATH_FILES.'product/'.$v0['product_id'].'/'.$v0['cover'], 'jpg', 228, 152);
								echo '<article class="box excerpt" title="'.$v0['service_name'].' | '.$v0['name'].'">
									<a href="'.url('detail', 'index', ['id'=>$v0['product_id']]).'" class="image"><img onerror="this.src=\''.static_file('images/origin.png').'\'" src="'.URL_FILES.'product/'.$v0['product_id'].'/'.sinechat_Thumbnail($v0['cover'], 228, 152).'" width="228" height="152"></a>
								</article>';
							}
						}
					?>
				</li>
			</ul>
		</section>
	</div>
	
	<div id="sidebar" class="9u 12u(mobile) ">
	<!-- Excerpts -->
		<section>
			<div>
				<article class="box post">
					<header><h2><i class="fa fa-gavel">&nbsp;</i><strong><?php echo $product['name'] ?></strong> </h2></header>
				</article>
			</div>
			<header>
				<h2 style="border-bottom: 2px #d0d0d0 solid; width:28%;margin-top:2em;">案例實景</h2>
			</header>
			<ul class="divided">
				<li>
					<article class="box excerpt">
						<div id="social_share" class="social-likes" data-url="<?php echo $web_url ?>" data-title="<?php echo $web_title ?>">
							<div class="facebook" title="Share link on Facebook">Facebook</div>
							<div class="twitter" title="Share link on Twitter">Twitter</div>
							<div class="plusone" title="Share link on Google+">Google+</div>
							<div class="line" title="Share link on Line">&nbsp;&nbsp;Line</div>
						</div>				
					</article>
				</li>
			</ul>
		</section>
	
		<section style="max-width: 750px;margin:0 4em;">
			<!-- Place somewhere in the <body> of your page -->
			<div id="slider" class="flexslider">
				<ul class="slides">
					<?php 
						if(is_array($a_image)) {
							foreach($a_image as $k0 => $v0) {
								if(is_file(PATH_FILES.'product/'.$product['product_id'].'/'.$v0)) image_reformat(PATH_FILES.'product/'.$product['product_id'].'/'.$v0, 'jpg', 750, 495);
								echo '<li><img src="'.URL_FILES.'product/'.$product['product_id'].'/'.sinechat_Thumbnail($v0, 750, 495).'" /></li>';
							}
						}
					?>
				</ul>
			</div>
			<div id="carousel" class="flexslider">
				<ul class="slides">
					<?php 
						if(is_array($a_image)) {
							foreach($a_image as $k0 => $v0) {
								if(is_file(PATH_FILES.'product/'.$product['product_id'].'/'.$v0)) image_reformat(PATH_FILES.'product/'.$product['product_id'].'/'.$v0, 'jpg', 72, 72);
								echo '<li><img src="'.URL_FILES.'product/'.$product['product_id'].'/'.sinechat_Thumbnail($v0, 72, 72).'" /></li>';
							}
						}
					?>
				</ul>
			</div>
		</section>
		<section>
			<header>
				<h2 style="border-bottom: 2px #d0d0d0 solid; width:28%;margin-top:2em;"><a href="javascript:void(0)">案例介紹</a></h2>
			</header>
			<ul class="divided">
				<li style="font-size:1.2em;">
					<article class="box excerpt" style="min-height: 300px;">
						<?php echo htmlspecialchars_decode($product['content']);  ?>
					</article>
				</li>
			</ul>
		</section>
	</div>
</div>

<script>
$(window).load(function() {
 	//縮圖控制
	$('#carousel').flexslider({
		animation: "slide",
		controlNav: false,
		animationLoop: false,
		slideshow: false,
		itemWidth: 72,
		itemMargin: 5,
		asNavFor: '#slider'
	});

	//主要燈箱
	$('#slider').flexslider({
		animation: "fade",
		controlNav: false,
		animationLoop: false,
		slideshow: true,
		slideshowSpeed: 3000,
		sync: "#carousel",
		itemWidth: 750,
	});

});

	//line icon
	var socialLikesButtons = {
		line: {
			clickUrl: 'http://line.naver.jp/R/msg/text/?<?php echo $product['name'].'  -  '.$web_url; ?>',	
			pupupWidth: 650,
			popupHeight: 500,
		}
	};

	//initialize social
	$('#social_share').socialLikes({
		url: '<?php echo $web_url ?>',
		title: '<?php echo $web_title; ?>',
	    counters: true,
	    singleTitle: 'Share it!',
	});

	//counter link
	$('#social_share').on('popup_closed.social-likes', function(event, service) {
	    $(event.currentTarget).socialLikes({forceUpdate: true});
	    var counter = $(event.currentTarget).find('.social-likes__counter_' + service);
	    counter.text(+(counter.text()||0)+1).removeClass('social-likes__counter_empty');
	});

</script>

<script type="text/javascript" src="//media.line.me/js/line-button.js?v=20140411"></script>