<div class="row">
	<div class="12u 12u(mobile)">
		<ol class="breadcrumb">
			<li><a href="<?php echo url(); ?>"><i class="fa fa-home"></i> Home</a></li>
			<li><a href="<?php echo url('product', 'index'); ?>">成果展示</a></li>
			<li class="active"><?php echo $data['name'] ?></li>
		</ol>
	</div>

	<!-- Other -->
	<div id="content" class="3u 12u(mobile) important(mobile) content_other" >
		<section>
			<div>
				<article class="box post">
					<header><h2>&nbsp;<strong></strong> </h2></header>
				</article>
			</div>
			<header>
				<h2 style="border-bottom: 2px #d0d0d0 solid; margin-top:2em;width:55%;">其他作品</h2>
			</header>
			<ul class="divided">
				<li style="width:90%">
					<?php 
						if(!empty($other) && is_array($other)) {
							foreach($other as $k0 => $v0) {
								image_reformat(PATH_FILES.'product/'.$v0['product_id'].'/'.$v0['cover'], 'jpg', 228, 152);
								echo '<article class="box excerpt">
									<a href="'.url('detail', 'index', ['id'=>$v0['product_id']]).'" class="image"><img src="'.URL_FILES.'product/'.$v0['product_id'].'/'.sinechat_Thumbnail($v0['cover'], 228, 152).'"></a>
								</article>';
							}
						}
					
					?>
				</li>
			</ul>
		</section>
	</div>
	
	<div id="sidebar" class="9u 12u(mobile) ">
	<!-- Excerpts -->
		<section>
			<div>
				<article class="box post">
					<header><h2><i class="fa fa-gavel">&nbsp;</i><strong><?php echo $data['name'] ?></strong> </h2></header>
				</article>
			</div>
			<header>
				<h2 style="border-bottom: 2px #d0d0d0 solid; width:25%;margin-top:2em;">案例實景</h2>
			</header>
			<ul class="divided">
				<li>
					<article class="box excerpt">
					</article>
				</li>
			</ul>
		</section>
	
		<section>
			<div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 750px; height: 600px; overflow: hidden; visibility: hidden; background-color: #24262e;">
				<!-- Loading Screen -->
				<div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
					<div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
					<div style="position:absolute;display:block;background:url('img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
				</div>
				<div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 750px; height: 500px; overflow: hidden;">
					<?php 
						if(is_array($a_image)) {
							foreach($a_image as $k0 => $v0) {
								image_reformat(PATH_FILES.'product/'.$data['product_id'].'/'.$v0, 'jpg', 750, 500);
								image_reformat(PATH_FILES.'product/'.$data['product_id'].'/'.$v0, 'jpg', 72, 72);
								echo '<div data-p="144.50" style="display: none;">
									<img data-u="image" src="'.URL_FILES.'product/'.$data['product_id'].'/'.sinechat_Thumbnail($v0, 750, 500).'" />
									<img data-u="thumb" src="'.URL_FILES.'product/'.$data['product_id'].'/'.sinechat_Thumbnail($v0, 72, 72).'" />
								</div>';
							}
						}
					?>
				</div>
				<div data-u="thumbnavigator" class="jssort01" style="background-color: rgba(240, 240, 240, 0.96);position:absolute;left:0px;bottom:0px;width:750px;height:100px;" data-autocenter="1">
					<div data-u="slides" style="cursor: default;">
						<div data-u="prototype" class="p">
							<div class="w">
								<div data-u="thumbnailtemplate" class="t"></div>
							</div>
							<div class="c"></div>
						</div>
					</div>
				</div>
				<span data-u="arrowleft" class="jssora05l" style="top:158px;left:8px;width:40px;height:200px;"></span>
				<span data-u="arrowright" class="jssora05r" style="top:158px;right:8px;width:40px;height:200px;"></span>
				<a href="http://www.jssor.com" style="display:none">Slideshow Maker</a>
			</div>
		</section>
		<section>
			<header>
				<h2 style="border-bottom: 2px #d0d0d0 solid; width:25%;margin-top:2em;"><a href="#">案例介紹</a></h2>
			</header>
			<ul class="divided">
				<li style="font-size:1.2em;">
						<article class="box excerpt">
							<?php echo htmlspecialchars_decode($data['content']);  ?>
						</article>

				</li>
			</ul>
		</section>
		

	</div>
</div>

<script>
   jQuery(document).ready(function ($) {
            var jssor_1_SlideshowTransitions = [
              {$Duration:1200,x:0.3,$During:{$Left:[0.3,0.7]},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:-0.3,$SlideOut:true,$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:-0.3,$During:{$Left:[0.3,0.7]},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:0.3,$SlideOut:true,$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,y:0.3,$During:{$Top:[0.3,0.7]},$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,y:-0.3,$SlideOut:true,$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,y:-0.3,$During:{$Top:[0.3,0.7]},$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,y:0.3,$SlideOut:true,$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:0.3,$Cols:2,$During:{$Left:[0.3,0.7]},$ChessMode:{$Column:3},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:0.3,$Cols:2,$SlideOut:true,$ChessMode:{$Column:3},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,y:0.3,$Rows:2,$During:{$Top:[0.3,0.7]},$ChessMode:{$Row:12},$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,y:0.3,$Rows:2,$SlideOut:true,$ChessMode:{$Row:12},$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,y:0.3,$Cols:2,$During:{$Top:[0.3,0.7]},$ChessMode:{$Column:12},$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,y:-0.3,$Cols:2,$SlideOut:true,$ChessMode:{$Column:12},$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:0.3,$Rows:2,$During:{$Left:[0.3,0.7]},$ChessMode:{$Row:3},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:-0.3,$Rows:2,$SlideOut:true,$ChessMode:{$Row:3},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:0.3,y:0.3,$Cols:2,$Rows:2,$During:{$Left:[0.3,0.7],$Top:[0.3,0.7]},$ChessMode:{$Column:3,$Row:12},$Easing:{$Left:$Jease$.$InCubic,$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:0.3,y:0.3,$Cols:2,$Rows:2,$During:{$Left:[0.3,0.7],$Top:[0.3,0.7]},$SlideOut:true,$ChessMode:{$Column:3,$Row:12},$Easing:{$Left:$Jease$.$InCubic,$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,$Delay:20,$Clip:3,$Assembly:260,$Easing:{$Clip:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,$Delay:20,$Clip:3,$SlideOut:true,$Assembly:260,$Easing:{$Clip:$Jease$.$OutCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,$Delay:20,$Clip:12,$Assembly:260,$Easing:{$Clip:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,$Delay:20,$Clip:12,$SlideOut:true,$Assembly:260,$Easing:{$Clip:$Jease$.$OutCubic,$Opacity:$Jease$.$Linear},$Opacity:2}
            ];
            
            var jssor_1_options = {
              $AutoPlay: true,
              $SlideshowOptions: {
                $Class: $JssorSlideshowRunner$,
                $Transitions: jssor_1_SlideshowTransitions,
                $TransitionsOrder: 1
              },
              $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$
              },
              $ThumbnailNavigatorOptions: {
                $Class: $JssorThumbnailNavigator$,
                $Cols: 10,
                $SpacingX: 8,
                $SpacingY: 8,
                $Align: 360
              }
            };
            
            var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);
            
            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizing
            function ScaleSlider() {
                var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
                if (refSize) {
                    refSize = Math.min(refSize, 750);
                    jssor_1_slider.$ScaleWidth(refSize);
                }
                else {
                    window.setTimeout(ScaleSlider, 30);
                }
            }
            ScaleSlider();
            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end
        });
</script>