<section class="content-header">
	<h1>新誠修繕工程  後台管理系統</h1>
	<ol class="breadcrumb">
		<li><a href="javascript:void(0)"><i class="fa fa-dashboard"></i> Home</a></li>
	</ol>
</section>

<!-- Main content -->
<section class="content">
	<div class="row">
		<div class="col-md-6 col-sm-12 col-xs-12 ">
			<div class="box box-danger">
				<div class="box-header with-border">
					<h3 class="box-title">案件類型</h3>
					<div class="box-tools pull-right">
						<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
						<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
					</div>
				</div>
				<div class="box-body">
					<div style="float:left;" class="col-md-8 col-sm-12 col-xs-12">
						<canvas id="pieChart" style="height:250px"></canvas>
					</div>
					<div style="float:left;" class="col-md-4 col-sm-12 col-xs-12">
						<ul class="list-unstyled">							
	 						<?php 
	 							if($pie_data != null) {
		 							foreach (json_decode($pie_data, true) as $k0 => $v0) {
		 								echo '<li style="margin-top:5px;"><span class="label" style="background-color:'.$v0['color'].';">&nbsp;&nbsp;</span>&nbsp;&nbsp;&nbsp;&nbsp;'.$v0['label'].' ： '.$v0['value'].'</li>';
		 							}
		 						}
	 						?>
	 					</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<script>
$(function () {
	/* Pie chars */
	var ctx = $("#pieChart").get(0).getContext("2d");
	var data = <?php print_r( $pie_data); ?>;

    var pieOptions = {
      //Boolean - Whether we should show a stroke on each segment
      segmentShowStroke: true,
      //String - The colour of each segment stroke
      segmentStrokeColor: "#fff",
      //Number - The width of each segment stroke
      segmentStrokeWidth: 2,
      //Number - The percentage of the chart that we cut out of the middle
      percentageInnerCutout: 0, // This is 0 for Pie charts
      //Number - Amount of animation steps
      animationSteps: 150,
      //String - Animation easing effect
      animationEasing: "easeOutBounce",
      //Boolean - Whether we animate the rotation of the Doughnut
      animateRotate: true,
      //Boolean - Whether we animate scaling the Doughnut from the centre
      animateScale: false,
      //Boolean - whether to make the chart responsive to window resizing
      responsive: true,
      // Boolean - whether to maintain the starting aspect ratio or not when responsive, if set to false, will take up entire container
      maintainAspectRatio: true,
      //String - A legend template
      legendTemplate: "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<segments.length; i++){%><li><span style=\"background-color:<%=segments[i].fillColor%>\"></span><%if(segments[i].label){%><%=segments[i].label%><%}%></li><%}%></ul>"
    };	
	var myNewChart = new Chart(ctx).Pie(data, pieOptions);
		
});
</script>