<section class="content-header">
	<h1>新誠修繕工程  後台管理系統</h1>
	<ol class="breadcrumb">
		<li><a href="javascript:void(0)"><i class="fa fa-dashboard"></i> Home</a></li>
	</ol>
</section>

<!-- Main content -->
<section class="content">
<div class="row">
  <div class="col-md-4 col-sm-12 col-xs-12 ">
    <div class="box box-danger">
      <div class="box-header with-border">
        <h4>案件類型 : <?php echo $service_count; ?> / 案件總數 : <?php echo $product_count; ?></h4>
        <div class="box-tools pull-right">
          <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
          <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
      </div>
      <div class="box-body">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <canvas id="pieChart" style="height:200px"></canvas>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6 col-sm-12 col-xs-12 ">
		<div class="box box-danger">
			<div class="box-body">
				<div class="col-md-12 col-sm-12 col-xs-12">
					 <canvas id="bar"></canvas>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-md-10 col-sm-12 col-xs-12 ">
		<div class="box box-info">
			<div class="box-header with-border">
				<h4>網站瀏覽人數 / 案件新增數量</h4>
				<div class="box-tools pull-right">
					<button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
					<button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
				</div>
			</div>
			<div class="box-body">            
				<div style="float:left;" class="col-md-11 col-sm-11 col-xs-11">
                    <div id="line_charts_tips" class="alert alert-danger alert-dismissible" style="display: none;">
                        <h4><i class="icon fa fa-ban"></i></h4>手機版無法顯示線型圖表
                    </div>
				 	<canvas id="lineChart" style="max-height:550px"></canvas>
				</div>
			</div>
		</div>
	</div>
</div>
</section>
<script>
$(function () {
    //-------------
    //- Pie CHART -
    //--------------
    var randomColorFactor = function() {
        return Math.round(Math.random() * 255);
    };
    var randomColor = function(opacity) {
        return 'rgba(' + randomColorFactor() + ',' + randomColorFactor() + ',' + randomColorFactor() + ',' + (opacity || '.3') + ')';
    };

    var config = {
        type: 'pie',
        data: {
            datasets: [{
                data: [<?php foreach ($pie_data as $k0 => $v0) { echo '"'.$v0['value'].'",';} ?>],
                backgroundColor: [<?php foreach ($pie_data as $k0 => $v0) { echo 'randomColor(0.8),';} ?>],
            }],
            labels: [<?php foreach ($pie_data as $k0 => $v0) { echo '"'.$v0['label'].'",';} ?>],
        },
        options: {
            responsive: true
        },
    };

    var ctx = document.getElementById("pieChart").getContext("2d");
    window.myPie = new Chart(ctx, config);
	 
    //-------------
    //- Bar CHART -
    //--------------
    var randomScalingFactor = function() {
        return (Math.random() > 0.5 ? 1.0 : -1.0) * Math.round(Math.random() * 100);
    };
    var randomColorFactor = function() {
        return Math.round(Math.random() * 255);
    };
    var randomColor = function() {
        return 'rgba(' + randomColorFactor() + ',' + randomColorFactor() + ',' + randomColorFactor() + ',.7)';
    };

    var barChartData = {
        labels: [
            <?php 
                foreach ($bar_data as $k0 => $v0) { 
                    echo ($k0 < 5 ) ? '"~'.date('m/d', strtotime($v0['date'])).'",' : '"~'.$v0['date'].'",';
                }
            ?>
        ],
        datasets: [{
            label: '案件新增(週)',
            backgroundColor: "#108199",
            data: [<?php foreach ($bar_data as $k0 => $v0) { echo '"'.$v0['data'].'",';}  ?>]
        }]

    };

    var ctx = document.getElementById("bar").getContext("2d");
    window.myBar = new Chart(ctx, {
        type: 'bar',
        data: barChartData,
        options: {
            responsive: true,
            legend: {
                position: 'top',
            },
            title: {
                display: true,
                text: '案件新增統計',
                fontSize : 22,
            },
            scales: {
                xAxes: [{
                        stacked: true,
                }],
                yAxes: [{
                        stacked: true,
                        ticks: {
                            min: 0,
                            stepSize: 1,
                            suggestedMax : 5,
                        }
                }]
            }
        
        },
      
    });

    //-------------
    //- LINE CHART -
    //--------------
    var config = {
        type: 'line',
        data: {
            labels: [<?php foreach ($line_data as $k0 => $v0) { echo '"'.date('m/d', strtotime($v0['date'])).'",';}  ?>],
            datasets: [{
              label: "網站瀏覽人數",
              fill: false,
              backgroundColor : '#46BFBD',
              borderColor : '#46BFBD',
              borderWidth : 2,
              pointBorderColor : '#46BFBD',
              pointBackgroundColor : '#46BFBD',
              pointBorderWidth : 2,
              data: [<?php foreach ($line_data as $k0 => $v0) { echo '"'.$v0['count'].'",';}  ?>]
            },
            {
              label: "案件新增數量",
              fill: false,
              backgroundColor : '#5B90BF',
              borderColor : '#5B90BF',
              borderWidth : 4,
              pointBorderColor : '#5B90BF',
              pointBackgroundColor : '#5B90BF',
              pointBorderWidth : 3,
              data: [<?php foreach ($a_line_product_num as $k0 => $v0) { echo '"-'.$v0.'",';}  ?>]
            }]
        },
        options: {
            responsive: true,
            title:{
                display:true,
                text:'網站瀏覽人數 / 案件新增數量',
                fontSize : 22,
            },
            tooltips: {
                mode: 'label',
                titleFontSize : 16,
                bodyFontSize : 14,
                callbacks: {
                    
                }
            },
            hover: {
                mode: 'dataset'
            },
            scales: {
                xAxes: [{
                    display: true,
                    scaleLabel: {
                        show: true,
                        labelString: 'Day'
                    }
                }],
                yAxes: [{
                    display: true,
                    scaleLabel: {
                        show: true,
                        labelString: 'Value'
                    },
                     ticks: {
                    }
                }]
            }
        }
    };

    var ctx = document.getElementById("lineChart").getContext("2d");
    if(window.outerWidth > 1240 ) {
        window.myLine = new Chart(ctx, config);
        $('div#line_charts_tips').hide();
    }else{
        $('div#line_charts_tips').show();
    }
});
</script>