<section class="content-header">
	<div class="box-body"><h2>修改密碼</h2></div>
	<h1>				
		<small><p class="text-light-blue"></p></small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="<?php echo url('admin', 'index') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">修改密碼</li>
	</ol>
</section>
<section class="content">
	<div class="box">
		<div class="box-body">
			<div class="row">
				<div class="col-md-10">
					<div class="box-body box-solid">
						<div class="box-header with-border">
							<i class="fa fa-file-text-o"></i>
							<h3 class="box-title"> 修改密碼 </h3>
						</div>
						<div class="box-body">
							<dl class="dl-horizontal">
								<dt>輸入舊密碼:</dt>
								<dd><input type="password" class="form-control" name="oldpassword" style="width:40%"></dd><br>
								
								<dt>輸入新密碼:</dt>
								<dd><input type="password" class="form-control" name="newpassword" style="width:40%"></dd><br>
								
								<dt>再次輸入新密碼:</dt>
								<dd><input type="password" class="form-control" name="checkpassword" style="width:40%"></dd><br>
								
							</dl>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<a class="btn btn-app" id="save">
	<i class="fa fa-save"></i> 修改(Save)
</a>

<script>

$(function () {
	$('#save').on('click', function(){
		let oldpassword = $('input[name="oldpassword"]').val(), newpassword = $('input[name="newpassword"]').val(), checkpassword = $('input[name="checkpassword"]').val()
		
		if(oldpassword == '' || newpassword == '' || checkpassword == '') {
			r = {'message':'請輸入修改資料'};
			_jbox(r, 'error');			
		}else{			
			$.post('<?php echo url('admin', 'admin') ?>' , {
				oldpassword : oldpassword,
				newpassword : newpassword,
				checkpassword : checkpassword,
			},function(r){
				r = $.parseJSON(r);
				if(r.result == 1) {
					_jbox(r, 'success');
				}else{
					_jbox(r, 'error');			
				}
			});
		}
	});
	
});

</script>