<div><input type="button" value="click!!" onclick="trackComment()">
<div id="disqus_thread"></div>
<script>
	function trackComment(comment) {
		$.post('<?php echo url('disqus', 'index') ?>' , {

		},function(r){
			r = $.parseJSON(r);
			processingBox.close();
			if(r.result == 1) {
				_jbox(r, 'success');
			}else{
				_jbox(r, 'error');			
			}
		});
	}

	var disqus_config = function () {
		this.page.shortname = 'ccckaass'; //固定值
		this.page.identifier = '<?php echo md5(url('comment', 'index', ['id'=>$id ])); ?>';
		this.page.url = '<?php echo url('comment', 'index', ['id'=>$id]) ;?>';
		this.callbacks.onNewComment = [
			function(comment) { 
				trackComment(comment);
			}
		];
	};

	(function() { // DON'T EDIT BELOW THIS LINE
	var d = document, s = d.createElement('script');
	s.src = '//ccckaass.disqus.com/embed.js';
	s.setAttribute('data-timestamp', +new Date());
	(d.head || d.body).appendChild(s);
	})();

	function _jbox(r, status) {
		var message = r.message;
		switch(status) {
			case 'error' :
				var icon = '<i style="color:#DD4B39;" class="fa fa-times-circle">';
			break;
			case 'success' :
				var icon = '<i style="color:#6FE060;" class="fa fa-check-circle">';
			break;
		}

		box = new jBox('Modal', {
			closeButton: 'title',
			delayOpen: 300,
			maxWidth: 600,
			minWidth: 100,
			title: '<span style="display: inline-block;height: 100%;vertical-align: middle;">'+icon+'</span>',
			onCloseComplete: function() {
				if (r.redirect) location.href = r.redirect;
			},
		}).setContent('<div >' + message + '</div>').open();
	}
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
</div>


<script id="dsq-count-scr" src="//ccckaass.disqus.com/count.js" async></script>



