<section class="content-header">
	<div class="box-body"><h2>修繕項目分類</h2></div>
	<h1>				
		<small><p class="text-light-blue"></p></small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="<?php echo url('admin', 'index') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">修繕項目分類</li>
	</ol>
</section>
<section class="content">
	<div class="box">
		<div class="box-body">
			<div class="row">
				<div class="col-md-10">
					<div class="box-body">
						<table id="example1" class="table table-bordered table-striped">
							<thead>
								<tr>
									<th>#</th>
									<th>編輯</th>
									<th>名稱</th>
									<th>排序</th>
									<th>修改時間</th>
									<th>狀態</th>
								</tr>
							</thead>
							<tbody>
								<?php 
								foreach($data as $k0 => $v0) {
								$status = ($v0['status']== 'open') ? '<span class="label label-success">OPEN</span>' : '<span class="label label-warning">CLOSE</span>';
									echo '<tr>
											<td>'.$v0['servicearea_id'].' </td>
											<td><a href="'.url('admin', 'servicearea/edit', ['servicearea_id'=>$v0['servicearea_id']]).'">編輯</a></td>
											<td><a href="'.url('admin', 'servicearea/edit', ['servicearea_id'=>$v0['servicearea_id']]).'">'.$v0['name'].'</a></td>
											<td>'.$v0['seqence'].' </td>
											<td>'.$v0['modify_time'].' </td>
											<td>'.$status.' </td>																
										</tr>';
								}
								?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
		<a class="btn btn-app" href="<?php echo url('admin', 'servicearea/edit'); ?>">
			<i class="fa fa-pencil"></i> 新增
		</a>
</section>
<script>
$(function () {
	$("#example1").DataTable({
		"order": [[ 0, "asc" ]],
	});
	
});

</script>