<div class="row">
	<div class="12u 12u(mobile) important(mobile)">
		<ol class="breadcrumb">
			<li><a href="<?php echo url(); ?>"><i class="fa fa-home"></i> Home</a></li>
			<li class="active">聯絡我們</li>
		</ol>
	</div>

	<!-- Content -->
	<div id="content" class="4u 12u(mobile) " >
		<section>
			<div>
				<article class="box post" style="font-size:80%">
					<header><h2 class="contact_info_title"><i class="fa fa-gavel">&nbsp;</i><strong>新誠修繕工程</strong> </h2></header>
				</article>
			</div>
			<header>
				<h2 style="border-bottom: 2px #d0d0d0 solid; margin-top:2em;width:50%;">聯絡資訊</h2>
			</header>
		</section>
		<section class="contact_info">
			<div class="row">
				<div class="12u 12u(mobile)" style="padding-left: 20px;">
					<ul class="icons">
						<?php
							foreach ($info as $k0 => $v0) { echo $v0; }
						?>
					</ul>
				</div>
			</div>
		</section>
	</div>
	
	<div id="sidebar" class="8u 12u(mobile) ">
	<!-- Excerpts -->
		<section>
			<div>
				<article class="box post">
					<header>&nbsp;</header>
				</article>
			</div>
			<header>
				<h2 style="border-bottom: 2px #d0d0d0 solid; width:50%;margin-top:2em;">聯絡我們</h2>
			</header>
		</section>
		<section>
			<form id="form_send" method="post" action="javascript:void(0)">
				<div class="row 50%" style="min-height:70px;">
					<div class="6u 12u(mobile)">
						<input name="name" placeholder="Name" type="text" required/>
					</div>
					<div class="6u 12u(mobile)">
						<input name="email" placeholder="Email" type="text"/>
					</div>
				</div>
				<div class="row 50%" style="min-height:70px;">
					<div class="6u 12u(mobile)">
						<input name="tel" placeholder="Tel" type="text" required/>
					</div>
					<div class="6u 12u(mobile)">
					性別:&nbsp;&nbsp;
						<label for="a" style="display:inline-block;margin-left:20px;">
							<input id="a" value="male" name="gender" type="radio" checked>  男
						</label>
						<label for="b"  style="display:inline-block;margin-left:20px;">
							<input id="b" value="female" name="gender" type="radio">  女
						</label>
					</div>
				</div>
				<div class="row 50%" style="min-height:200px;">
					<div class="12u">
						<textarea name="memo" id="memo" placeholder="Message"></textarea>
					</div>
				</div>
				<div class="row 50%" style="min-height:90px;">
					<div class="12u">
						<input type="submit" id="send" class="form-button-submit button icon fa-envelope" value="聯絡我們">
					</div>
				</div>
			</form>
		</section>
	</div>
</div>

<script>

	$('#form_send').on('submit', function(){
		var name = $('input[name="name"]').val(),email = $('input[name="email"]').val(),tel = $('input[name="tel"]').val(),gender = $('input[name="gender"]').val(),memo=$('#memo').val();
		var reg = /^[^\s]+@[^\s]+\.[^\s]{2,3}$/;

		if(name == '' || tel == '' || gender == '' || memo == '' ) {
			var r = {'message':'資料填寫不完全，請重新確認'};
			_jbox(r, 'error');
		} else if (!/^\d+$/.test(tel)) { 
			r = {'message': '電話號碼格式錯誤。'};
			_jbox(r, 'error');
		} else if(!reg.test(email)){
			r = {'message': '電子信箱格式錯誤。'};
			_jbox(r, 'error');
		} else {
			var processingBox = new jBox('Modal', {
				closeOnClick: false,
				closeButton: 'title',
				width: 140,
				height: 60,
				onOpen : function(){
					$.post('<?php echo url('contact', 'index') ?>' , {
						name : name ,
						email : email ,
						tel : tel ,
						gender : gender,
						memo : memo,
					},function(r){
						r = $.parseJSON(r);
						processingBox.close();
						if(r.result == 1) {
							_jbox(r, 'success');
						}else{
							_jbox(r, 'error');			
						}
					});
				},
			}).setContent('<span style="padding-left:20px;font-weight:bold;color:rgba(85, 85, 85, 0.8);">處理中...</span><img src="<?php echo URL_IMG.'loading.gif'?>">').open();
		}
	});

	function _jbox(r, status) {
		var message = r.message;
		switch(status) {
			case 'error' :
				var icon = '<i style="color:#DD4B39;" class="fa fa-times-circle">';
			break;
			case 'success' :
				var icon = '<i style="color:#6FE060;" class="fa fa-check-circle">';
			break;
		}

		box = new jBox('Modal', {
			closeButton: 'title',
			delayOpen: 300,
			maxWidth: 600,
			minWidth: 100,
			title: '<span style="display: inline-block;height: 100%;vertical-align: middle;">'+icon+'</span>',
			onCloseComplete: function() {
				if (r.redirect) location.href = r.redirect;
			},
		}).setContent('<div >' + message + '</div>').open();
	}

</script>