<div class="row">
	<div class="12u 12u(mobile) important(mobile)">
		<ol class="breadcrumb">
			<li><a href="<?php echo url(); ?>">Home</a></li>
			<li class="active">聯絡我們</li>
		</ol>
	</div>

	<!-- Content -->
	<div id="content" class="3u 12u(mobile) " >
		<section>
			<div>
				<article class="box post" style="font-size:80%">
					<header><h2 class="contact_info_title"><i class="fa fa-gavel">&nbsp;</i><strong>新誠居家修繕工程</strong> </h2></header>
				</article>
			</div>
			<header>
				<h2 style="border-bottom: 2px #d0d0d0 solid; margin-top:2em;width:50%;">聯絡資訊</h2>
			</header>
		</section>
		<section class="contact_info">
			<div class="row">
				<div class="12u 12u(mobile)">
					<ul class="icons">
						<li class="icon fa-home">
							新北市鶯歌區XX路XX巷XX號1樓
						</li>
						<li class="icon fa-phone">
							(00) 0000-0000
						</li>
						<li class="icon fa-envelope">
							<a href="#">chang@sinechat.com</a>
						</li>
					</ul>
				</div>
			</div>
		</section>
		
	</div>
	
	<div id="sidebar" class="9u 12u(mobile) ">
	<!-- Excerpts -->
		<section>
			<div>
				<article class="box post">
					<header>&nbsp;</header>
				</article>
			</div>
			<header>
				<h2 style="border-bottom: 2px #d0d0d0 solid; width:50%;margin-top:2em;">聯絡我們</h2>
			</header>
				
		</section>
		<section>
			<form method="post" action="#">
				<div class="row 50%" style="min-height:70px;">
					<div class="6u 12u(mobile)">
						<input name="name" placeholder="Name" type="text" />
					</div>
					<div class="6u 12u(mobile)">
						<input name="email" placeholder="Email" type="text" />
					</div>
				</div>
				<div class="row 50%" style="min-height:200px;">
					<div class="12u">
						<textarea name="message" placeholder="Message"></textarea>
					</div>
				</div>
				<div class="row 50%" style="min-height:90px;">
					<div class="12u">
						<a href="#" class="form-button-submit button icon fa-envelope">Send Message</a>
					</div>
				</div>
			</form>
		</section>
		

	</div>
</div>

<script>
</script>