<header class="main-header">
	<a href="javascript:void(0)" class="logo">
		<span class="logo-mini" style="font-size:14px;">Sinechat</span>
		<span class="logo-lg" style="font-size: 16px;"><b>Sinechat 管理系統</b> </span>
	</a>
	<nav class="navbar navbar-static-top" role="navigation">
		<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
			<span class="sr-only">Toggle navigation</span>
		</a>
	</nav>
</header>