<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<?php 
	//css file
	set_css('css/bootstrap.min.css');
	set_css('css/adminlte/AdminLTE.min.css');
	set_css('css/adminlte/_all-skins.min.css');
	set_css('js/icheck/all.css');
	set_css('js/jBox/jBox.css');
	set_css('css/font-awesome/css/font-awesome.css');

	//js file
	set_js('js/jquery.min.js');
	set_js('js/bootstrap-admin/js/bootstrap.min.js');
	set_js('js/adminlte/app.min.js');
	set_js('js/adminlte/demo.js');
	set_js('js/jBox/jBox.js');

/**
 * 不同分類引入各自的css/js file
 */
switch(_SUB_CLASS) {
	case 'about':
		set_js('js/slimscroll/jquery.slimscroll.min.js');
		set_js('js/fastclick/fastclick.min.js');
		set_js('js/ckeditor/ckeditor.js');
		set_js('js/ckeditor/adapters/jquery.js');
	break;

	case 'contact' :
		set_css('js/datatables/dataTables.bootstrap.css');
		set_css('js/jquery-ui-1.11.4/jquery-ui.min.css');
		set_css('js/icheck/minimal/minimal.css');

		set_js('js/datatables/jquery.dataTables.min.js');
		set_js('js/slimscroll/jquery.slimscroll.min.js');
		set_js('js/datatables/dataTables.bootstrap.min.js');
		set_js('js/jquery-ui-1.11.4/jquery-ui.min.js');
		set_js('js/jquery-ui-1.11.4/datepicker-zh-TW.js');
		set_js('js/icheck/icheck.min.js');	
	break;

	case 'news':
		set_css('js/datatables/dataTables.bootstrap.css');
		set_css('js/jquery-ui-1.11.4/jquery-ui.min.css');
		set_css('js/icheck/minimal/minimal.css');

		set_js('js/ckeditor/ckeditor.js');
		set_js('js/ckeditor/adapters/jquery.js');
		set_js('js/datatables/jquery.dataTables.min.js');
		set_js('js/slimscroll/jquery.slimscroll.min.js');
		set_js('js/datatables/dataTables.bootstrap.min.js');
		set_js('js/jquery-ui-1.11.4/jquery-ui.min.js');
		set_js('js/jquery-ui-1.11.4/datepicker-zh-TW.js');
		set_js('js/icheck/icheck.min.js');
		
	break;	
	
	case 'product':
		set_css('js/datatables/dataTables.bootstrap.css');
		set_css('js/jquery-ui-1.11.4/jquery-ui.min.css');
		set_css('js/icheck/minimal/minimal.css');
		set_css('js/jquert-fileupload/css/blueimp-gallery.min.css');
		set_css('js/jquert-fileupload/css/jquery.fileupload.css');
		set_css('js/jquert-fileupload/css/jquery.fileupload-ui.css');
		set_css('css/style.css');

		set_js('js/datatables/jquery.dataTables.min.js');
		set_js('js/slimscroll/jquery.slimscroll.min.js');
		set_js('js/datatables/dataTables.bootstrap.min.js');
		set_js('js/jquery-ui-1.11.4/jquery-ui.min.js');
		set_js('js/jquery-ui-1.11.4/datepicker-zh-TW.js');
		set_js('js/icheck/icheck.min.js');
		set_js('js/ckeditor/ckeditor.js');
		
		set_js('js/jquert-fileupload/js/jquery.ui.widget.js');
		echo '<script src="//blueimp.github.io/JavaScript-Templates/js/tmpl.min.js"></script>';
		echo '<script src="//blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>';
		echo '<script src="//blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>';
		echo '<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>';
		echo '<script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>';
		
		set_js('js/jquert-fileupload/js/jquery.iframe-transport.js');
		set_js('js/jquert-fileupload/js/jquery.fileupload.js');
		set_js('js/jquert-fileupload/js/jquery.fileupload-process.js');
		set_js('js/jquert-fileupload/js/jquery.fileupload-image.js');
		set_js('js/jquert-fileupload/js/jquery.fileupload-validate.js');
		set_js('js/jquert-fileupload/js/jquery.fileupload-ui.js');	
	break;	
	
	case 'service_ad':
		set_css('js/datatables/dataTables.bootstrap.css');
		set_css('js/jquery-ui-1.11.4/jquery-ui.min.css');
		set_css('js/icheck/minimal/minimal.css');
		set_js('js/ckeditor/ckeditor.js');
		set_js('js/ckeditor/adapters/jquery.js');
		set_js('js/datatables/jquery.dataTables.min.js');
		set_js('js/slimscroll/jquery.slimscroll.min.js');
		set_js('js/datatables/dataTables.bootstrap.min.js');
		set_js('js/jquery-ui-1.11.4/jquery-ui.min.js');
		set_js('js/jquery-ui-1.11.4/datepicker-zh-TW.js');
		set_js('js/icheck/icheck.min.js');
		
	break;	
		
	case 'service':
		set_css('js/datatables/dataTables.bootstrap.css');
		set_css('js/jquery-ui-1.11.4/jquery-ui.min.css');
		set_css('js/icheck/minimal/minimal.css');

		set_js('js/datatables/jquery.dataTables.min.js');
		set_js('js/slimscroll/jquery.slimscroll.min.js');
		set_js('js/datatables/dataTables.bootstrap.min.js');
		set_js('js/jquery-ui-1.11.4/jquery-ui.min.js');
		set_js('js/jquery-ui-1.11.4/datepicker-zh-TW.js');
		set_js('js/icheck/icheck.min.js');
		set_js('js/ckeditor/ckeditor.js');
		
	break;		

	case 'servicearea':
		set_css('js/datatables/dataTables.bootstrap.css');
		set_css('js/jquery-ui-1.11.4/jquery-ui.min.css');
		set_css('js/icheck/minimal/minimal.css');

		set_js('js/datatables/jquery.dataTables.min.js');
		set_js('js/slimscroll/jquery.slimscroll.min.js');
		set_js('js/datatables/dataTables.bootstrap.min.js');
		set_js('js/jquery-ui-1.11.4/jquery-ui.min.js');
		set_js('js/jquery-ui-1.11.4/datepicker-zh-TW.js');
		set_js('js/icheck/icheck.min.js');
	break;	

	case 'setbanner' : 
		set_css('js/datatables/dataTables.bootstrap.css');
		set_css('js/jquery-ui-1.11.4/jquery-ui.min.css');
		set_css('js/icheck/minimal/minimal.css');
		set_css('js/jquert-fileupload/css/blueimp-gallery.min.css');
		set_css('js/jquert-fileupload/css/jquery.fileupload.css');
		set_css('js/jquert-fileupload/css/jquery.fileupload-ui.css');
		set_css('css/style.css');

		set_js('js/datatables/jquery.dataTables.min.js');
		set_js('js/slimscroll/jquery.slimscroll.min.js');
		set_js('js/datatables/dataTables.bootstrap.min.js');
		set_js('js/jquery-ui-1.11.4/jquery-ui.min.js');
		set_js('js/jquery-ui-1.11.4/datepicker-zh-TW.js');
		set_js('js/icheck/icheck.min.js');
		set_js('js/ckeditor/ckeditor.js');
		
		set_js('js/jquert-fileupload/js/jquery.ui.widget.js');
		echo '<script src="//blueimp.github.io/JavaScript-Templates/js/tmpl.min.js"></script>';
		echo '<script src="//blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>';
		echo '<script src="//blueimp.github.io/JavaScript-Canvas-to-Blob/js/canvas-to-blob.min.js"></script>';
		echo '<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>';
		echo '<script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>';
		
		set_js('js/jquert-fileupload/js/jquery.iframe-transport.js');
		set_js('js/jquert-fileupload/js/jquery.fileupload.js');
		set_js('js/jquert-fileupload/js/jquery.fileupload-process.js');
		set_js('js/jquert-fileupload/js/jquery.fileupload-image.js');
		set_js('js/jquert-fileupload/js/jquery.fileupload-validate.js');
		set_js('js/jquert-fileupload/js/jquery.fileupload-ui.js');		
	break;

	case 'index' :
		set_js('js/chartjs/Chart.min.js');
		set_js('js/fastclick/fastclick.min.js');
	break;
	
	case 'info' :
		set_css('js/datatables/dataTables.bootstrap.css');
		set_css('js/jquery-ui-1.11.4/jquery-ui.min.css');
		set_css('js/icheck/minimal/minimal.css');

		set_js('js/datatables/jquery.dataTables.min.js');
		set_js('js/slimscroll/jquery.slimscroll.min.js');
		set_js('js/datatables/dataTables.bootstrap.min.js');
		set_js('js/jquery-ui-1.11.4/jquery-ui.min.js');
		set_js('js/icheck/icheck.min.js');
	break;

}

?>

