<aside class="main-sidebar">
	<section class="sidebar">
		<ul class="sidebar-menu">
			<li class="header">新誠居家修繕</li>
			<li>
				<a href="<?php echo url('admin'); ?>"><i class="fa fa-home"></i> <span>首頁</span></a>
			</li>
			<li>
				<a href="<?php echo url('admin', 'setbanner'); ?>"><i class="fa fa-file-photo-o"></i> <span>橫幅banner圖</span></a>
			</li>
		</ul>
		<ul class="sidebar-menu">
			<li class="header">關於新誠</li>
			<li>
				<a href="<?php echo url('admin', 'about') ?>"><i class="fa fa-info"></i> <span>關於新誠</span></a>
			</li>
		</ul>
		<ul class="sidebar-menu">
			<li class="header">最新消息</li>
			<li>
				<a href="<?php echo url('admin', 'news') ?>"><i class="fa fa-list-ol"></i> <span>最新消息管理</span></a>
			</li>
		</ul>
		<ul class="sidebar-menu">
			<li class="header">修繕項目</li>
			<li>
				<a href="<?php echo url('admin', 'servicearea') ?>"><i class="fa fa-file-text-o"></i> <span>修繕項目主類別</span></a>
			</li>
			<li>
				<a href="<?php echo url('admin', 'service') ?>"><i class="fa fa-gavel"></i> <span>修繕項目管理</span></a>
			</li>
		</ul>
		<ul class="sidebar-menu">
			<li class="header">成果展示</li>
			<li>
				<a href="<?php echo url('admin', 'product') ?>"><i class="fa fa-product-hunt"></i> <span>修繕作品管理</span></a>
			</li>
		</ul>
		<ul class="sidebar-menu">
			<li class="header">聯絡資訊 / 聯絡我們</li>
			<li>
				<a href="<?php echo url('admin', 'info') ?>"><i class="glyphicon glyphicon-phone-alt"></i> <span>新誠聯絡資訊設定</span></a>
			</li>
			<li>
				<a href="<?php echo url('admin', 'contact') ?>"><i class="fa fa-reply"></i> <span>聯絡我們 - 清單</span></a>
			</li>
		</ul>
		<ul class="sidebar-menu">
			<li class="header">登出</li>
			<li>
				<a href="<?php echo url('admin', 'logout') ?>"><i class="fa fa-sign-out"></i> <span>登出</span></a>
			</li>
		</ul>		<!--
		<ul class="sidebar-menu">
			<li class="header">聯繫我們 / 產品詢價</li>
			<li>
				<a href="javascript:void(0)"><i class="fa fa-reply"></i> <span>聯繫我們</span></a>
			</li>
			<li>
				<a href="javascript:void(0)"><i class="fa fa-question"></i> <span>產品詢價</span></a>
			</li>
		</ul>
		<ul class="sidebar-menu">
			<li class="header">系統</li>
			<li>
				<a href="javascript:void(0)"><i class="fa fa-gear"></i> <span>系統參數</span></a>
			</li>
			<li>
				<a href="javascript:void(0)"><i class="fa fa-list-ul"></i> <span>管理員設定</span></a>
			</li>
		</ul>
		-->
	</section>
</aside>
