<aside class="main-sidebar">
	<section class="sidebar">
		<ul class="sidebar-menu">
			<li class="header">新誠居家修繕</li>
			<li>
				<a href="<?php echo url('admin'); ?>"><i class="fa fa-home"></i> <span>首頁</span></a>
			</li>
		</ul>
		<ul class="sidebar-menu">
			<li class="header">關於新誠</li>
			<li>
				<a href="<?php echo url('admin', 'about') ?>"><i class="fa fa-info"></i> <span>關於新誠</span></a>
			</li>
		</ul>
		<ul class="sidebar-menu">
			<li class="header">最新消息</li>
			<li>
				<a href="<?php echo url('admin', 'news') ?>"><i class="fa fa-list-ol"></i> <span>最新消息</span></a>
			</li>
		</ul>


		<ul class="sidebar-menu">
			<li class="header">商品資訊</li>
			<li>
				<a href="javascript:void(0)"><i class="fa fa-list"></i> <span>產品類別區域管理</span></a>
			</li>
			<li>
				<a href="javascropt:void(0)"><i class="fa fa-list-ul"></i> <span>產品類別管理</span></a>
			</li>
			<li>
				<a href="javascropt:void(0)"><i class="fa fa-heart"></i> <span>產品管理</span></a>
			</li>
		</ul>
		<ul class="sidebar-menu">
			<li class="header">社群網站</li>
			<li>
				<a href="javascript:void(0)"><i class="fa fa-book"></i> <span>社群網站連結</span></a>
			</li>
		</ul>
		<ul class="sidebar-menu">
			<li class="header">聯繫我們 / 產品詢價</li>
			<li>
				<a href="javascript:void(0)"><i class="fa fa-reply"></i> <span>聯繫我們</span></a>
			</li>
			<li>
				<a href="javascript:void(0)"><i class="fa fa-question"></i> <span>產品詢價</span></a>
			</li>
		</ul>
		<ul class="sidebar-menu">
			<li class="header">系統</li>
			<li>
				<a href="javascript:void(0)"><i class="fa fa-gear"></i> <span>系統參數</span></a>
			</li>
			<li>
				<a href="javascript:void(0)"><i class="fa fa-list-ul"></i> <span>管理員設定</span></a>
			</li>
		</ul>
		<ul class="sidebar-menu">
			<li class="header">登出</li>
			<li>
				<a href="<?php echo url('admin', 'logout') ?>"><i class="fa fa-sign-out"></i> <span>登出</span></a>
			</li>
		</ul>
	</section>
</aside>
