<div id="content">
	<div class="12u 12u(mobile)">
		<ol class="breadcrumb">
			<li><a href="<?php echo url(); ?>"><i class="fa fa-home"></i> Home</a></li>
			<li class="active">關於新誠</li>
		</ol>
	</div>
	<article style="min-height:400px;" class="box post">
		<header><h2><i class="fa fa-gavel">&nbsp;</i><strong>關於新誠</strong> </h2></header>
		<div class="editor_content" style="padding:0 2em;width:100%;">
			<?php 
				if(!empty($data)) echo htmlspecialchars_decode($data['content']); 
			?>
			<div id="append_area"></div>
			<hr>
		</div>
	</article>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		$('.editor_content').find('img').each(function(k,v){
			var h_w = $(this).css(['height', 'width']);
			$(this).removeAttr('style').css('max-height', h_w.height).css('max-width', h_w.width);
			$(this).wrap('<span class="image"></div>'); 
		});
		
		$('td').css('vertical-align', 'top');
		
		
		$('table').css('width', 'auto');
		
		
		if($(window).width() <= 1080 ) {
			$('.editor_content').find('img').each(function(k,v){
				let src = $(this).attr('src'), 
				width = $(this).css('max-width'), 
				height = $(this).css('max-height'), 
				obj = '<p><span class="image"><img src="'+src+'" style="max-height:'+height+'; max-width:'+width+'"></span></p>';
				
				$(this).parent('span').hide();
				$('div#append_area').append(obj);
			});
		}
	});
</script>