<div id="content">
	<div class="12u 12u(mobile)">
		<ol class="breadcrumb">
			<li><a href="<?php echo url(); ?>"><i class="fa fa-home"></i> Home</a></li>
			<li class="active">關於新誠</li>
		</ol>
	</div>
	<article style="min-height:400px;" class="box post">
		<header><h2><i class="fa fa-gavel">&nbsp;</i><strong>關於新誠</strong> </h2></header>
		<div class="editor_content table-responsive" style="padding:0 2em;width:100%;">
			<?php 
				if(!empty($data)) echo htmlspecialchars_decode($data['content']); 
			?>
			<hr>
		</div>
	</article>
</div>
<div id="show_photo" style="display:none;"></div>
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>
<script type="text/javascript">
	$(document).ready(function() {
		$('.editor_content').find('img').each(function(k,v) {
			var h_w = $(this).css(['height', 'width']);
			$(this).removeAttr('style').css('max-height', h_w.height).css('max-width', h_w.width).addClass('editor_content');
			$(this).wrap('<a href="javascript:void(0)" class="show_photo" data-link="'+k+'"><span class="image"></span></a>'); 
			$('#show_photo').append('<a href="'+$(this).attr('src')+'"><img src="'+$(this).attr('src')+'"></a>');
		});
		
		$('td').css('vertical-align', 'top');
		$('table').addClass('table').css('width', 'auto');
		
		$('.show_photo').on('click' ,function() {
			$('#show_photo').trigger('click', $(this).data('link'));
		});
	});

	document.getElementById('show_photo').onclick = function (event, v) {
		event = event || window.event;
		var target = event.target || event.srcElement,
			link = v;
			options = {index: link, event: event},
			links = this.getElementsByTagName('a');
		blueimp.Gallery(links, options);
	};


</script>