<div class="row">
	<div class="12u 12u(mobile)">
		<ol class="breadcrumb">
			<li><a href="<?php echo url(); ?>"><i class="fa fa-home"></i> Home</a></li>
			<li><a href="<?php echo url('product', 'index'); ?>">成果展示</a></li>
			<li class="active">鶯歌新誠居家修繕</li>
		</ol>
	</div>

	<!-- Content -->
	<div id="content" class="3u 12u(mobile) important(mobile) content_other" >
		<section>
			<div>
				<article class="box post">
					<header><h2>&nbsp;<strong></strong> </h2></header>
				</article>
			</div>
			<header>
				<h2 style="border-bottom: 2px #d0d0d0 solid; margin-top:2em;width:55%;">其他作品</h2>
			</header>
			<ul class="divided">
				<li style="width:90%">
					<article class="box excerpt">
						<a href="javascript:void(0)" class="image"><img src="<?php echo static_file('images/slider/10.jpg') ?>"></a>
					</article>
					<article class="box excerpt">
						<a href="javascript:void(0)" class="image"><img src="<?php echo static_file('images/slider/11.jpg') ?>"></a>
					</article>
					<article class="box excerpt">
						<a href="javascript:void(0)" class="image"><img src="<?php echo static_file('images/slider/09.jpg') ?>"></a>
					</article>
					<article class="box excerpt">
						<a href="javascript:void(0)" class="image"><img src="<?php echo static_file('images/slider/12.jpg') ?>"></a>
					</article>
					<article class="box excerpt">
						<a href="javascript:void(0)" class="image"><img src="<?php echo static_file('images/5.jpg') ?>"></a>
					</article>
					<article class="box excerpt">
						<a href="javascript:void(0)" class="image"><img src="<?php echo static_file('images/6.jpg') ?>"></a>
					</article>

				</li>
			</ul>
		</section>
	</div>
	
	<div id="sidebar" class="9u 12u(mobile) ">
	<!-- Excerpts -->
		<section>
			<div>
				<article class="box post">
					<header><h2><i class="fa fa-gavel">&nbsp;</i><strong>鶯歌新誠居家修繕</strong> </h2></header>
				</article>
			</div>
			<header>
				<h2 style="border-bottom: 2px #d0d0d0 solid; width:25%;margin-top:2em;">案例實景</h2>
			</header>
			<ul class="divided">
				<li>
					<article class="box excerpt">
						
					</article>

				</li>
			</ul>
		</section>
	
		<section>
			<div id="jssor_1" style="position: relative; margin: 0 auto; top: 0px; left: 0px; width: 800px; height: 456px; overflow: hidden; visibility: hidden; background-color: #24262e;">
				<!-- Loading Screen -->
				<div data-u="loading" style="position: absolute; top: 0px; left: 0px;">
					<div style="filter: alpha(opacity=70); opacity: 0.7; position: absolute; display: block; top: 0px; left: 0px; width: 100%; height: 100%;"></div>
					<div style="position:absolute;display:block;background:url('img/loading.gif') no-repeat center center;top:0px;left:0px;width:100%;height:100%;"></div>
				</div>
				<div data-u="slides" style="cursor: default; position: relative; top: 0px; left: 0px; width: 800px; height: 356px; overflow: hidden;">
					<div data-p="144.50" style="display: none;">
						<img data-u="image" src="<?php echo static_file('images/slider/01.jpg') ?>" />
						<img data-u="thumb" src="<?php echo static_file('images/slider/thumb-01.jpg') ?>" />
					</div>
					<div data-p="144.50" style="display: none;">
						<img data-u="image" src="<?php echo static_file('images/slider/02.jpg') ?>" />
						<img data-u="thumb" src="<?php echo static_file('images/slider/thumb-02.jpg') ?>" />
					</div>
					<div data-p="144.50" style="display: none;">
						<img data-u="image" src="<?php echo static_file('images/slider/03.jpg') ?>" />
						<img data-u="thumb" src="<?php echo static_file('images/slider/thumb-03.jpg') ?>" />
					</div>
					<div data-p="144.50" style="display: none;">
						<img data-u="image" src="<?php echo static_file('images/slider/04.jpg') ?>" />
						<img data-u="thumb" src="<?php echo static_file('images/slider/thumb-04.jpg') ?>" />
					</div>
					<div data-p="144.50" style="display: none;">
						<img data-u="image" src="<?php echo static_file('images/slider/05.jpg') ?>" />
						<img data-u="thumb" src="<?php echo static_file('images/slider/thumb-05.jpg') ?>" />
					</div>
					<div data-p="144.50" style="display: none;">
						<img data-u="image" src="<?php echo static_file('images/slider/06.jpg') ?>" />
						<img data-u="thumb" src="<?php echo static_file('images/slider/thumb-06.jpg') ?>" />
					</div>
					<div data-p="144.50" style="display: none;">
						<img data-u="image" src="<?php echo static_file('images/slider/07.jpg') ?>" />
						<img data-u="thumb" src="<?php echo static_file('images/slider/thumb-07.jpg') ?>" />
					</div>
					<div data-p="144.50" style="display: none;">
						<img data-u="image" src="<?php echo static_file('images/slider/08.jpg') ?>" />
						<img data-u="thumb" src="<?php echo static_file('images/slider/thumb-08.jpg') ?>" />
					</div>
					<div data-p="144.50" style="display: none;">
						<img data-u="image" src="<?php echo static_file('images/slider/09.jpg') ?>" />
						<img data-u="thumb" src="<?php echo static_file('images/slider/thumb-09.jpg') ?>" />
					</div>
				</div>
				<!-- Thumbnail Navigator -->
				<div data-u="thumbnavigator" class="jssort01" style="background-color: rgba(240, 240, 240, 0.96);position:absolute;left:0px;bottom:0px;width:800px;height:100px;" data-autocenter="1">
					<!-- Thumbnail Item Skin Begin -->
					<div data-u="slides" style="cursor: default;">
						<div data-u="prototype" class="p">
							<div class="w">
								<div data-u="thumbnailtemplate" class="t"></div>
							</div>
							<div class="c"></div>
						</div>
					</div>
					<!-- Thumbnail Item Skin End -->
				</div>
				<!-- Arrow Navigator -->
				<span data-u="arrowleft" class="jssora05l" style="top:158px;left:8px;width:40px;height:40px;"></span>
				<span data-u="arrowright" class="jssora05r" style="top:158px;right:8px;width:40px;height:40px;"></span>
				<a href="http://www.jssor.com" style="display:none">Slideshow Maker</a>
			</div>
		</section>
		<section>
			<header>
				<h2 style="border-bottom: 2px #d0d0d0 solid; width:25%;margin-top:2em;"><a href="#">案例介紹</a></h2>
			</header>
			<ul class="divided">
				<li style="font-size:1.2em;">
						<article class="box excerpt">
							<p>
								重點 1　掌握10原則挑「好」的水泥工 在沒有設計師幫忙監工的保護傘下，盡量找親朋好友先介紹認識的泥水工洽談，除了施工品質可以先有參考依據外，也可以較容易找到人品誠懇實在的師傅，在比較的同時，也別貪心，有多少預算做多少事，施工實在、品質好才是最重要的。 
							</p>
							<p>
								重點 2　估價單是否確實 在施工前一定要請工班師傅看過現場，這樣估價單才會精準。而且在看現場的過程中，好的師傅會提供中肯的建議，像是地平不平？需不需刨掉打底？需不需要上粉光？或是建議只要舖木地板就好等等。若是找了一家以上的工班估價，估價單內的坪數、施工內容是否一致，都要仔細確認。以總價的高低來選擇工班不一定正確，有 時選到價格較低的工班，但若估價階段不確實，例如坪數少估等，結果施工一半還要追加預算，反而讓人覺得不舒服。
							</p>
							<p>
								重點 3　要先確認付款方式 如果工程規模不大，一般師傅可以接受工程完工後一次付清。但大部份都會先要求支付訂金，如果是含工帶料，一般支付訂金是合理的，師傅也會怕收不到錢。就算不含料，師傅的工資也都包含搬運材料及泥作的善後清理，這一點要清楚。有些師傅可以接受預留一些尾款10％，待整體交屋後付清，在交屋前若有需要修補的地方，都可以請師傅幫忙。
							</p>
							<p>
								重點 4　會協助確認進料品質 泥作師傅的經驗多為十幾年，甚至三、四十年，所承作的工程經驗豐富，好的師傅會協助確認進料的品質，例如地磚、壁磚是否平整、有沒有缺角、新購買的馬桶或浴缸在進貨時是否完整……等等的問題。
							</p>
							<p>
								重點 5　會幫屋主設想沒注意到的地方 熱心的師傅會貼心的幫屋主設想周全，像是檯面及浴室地板止水條的設計、浴缸底部用紅磚強化……等等。雖然是一些小地方，但處理妥當，對屋主來說，未來在使用上才可以方便又安全，最重要才能使用長長久久。
							</p>
							<p>
								重點 6　防水工程有保固 泥作最重要的一環，就是防水。大致來說，屋頂、陽台、浴室等一定會有泥作的防水工程，一般人或許搞不清師傅防水施作的好壞，所以是否提供保固就很重要了，一般來說多半提供一年的保固期，所以在發包前最好跟工班師傅確認，才有保障。當然如果預算夠，選用較好的防水材，使用期也會拉長，而室內、室外所使用的防水材也不同，都可以先確認。
							</p>
							<p>
								內容來源：泥作工程 裝潢維基百科 | Searchome設計家_漂亮家居
								http://www.searchome.net/wikientry.aspx?entry=%E6%B3%A5%E4%BD%9C%E5%B7%A5%E7%A8%8B#toc_1
							</p>
						</article>

				</li>
			</ul>
		</section>
		

	</div>
</div>

<script>
   jQuery(document).ready(function ($) {
            
            var jssor_1_SlideshowTransitions = [
              {$Duration:1200,x:0.3,$During:{$Left:[0.3,0.7]},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:-0.3,$SlideOut:true,$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:-0.3,$During:{$Left:[0.3,0.7]},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:0.3,$SlideOut:true,$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,y:0.3,$During:{$Top:[0.3,0.7]},$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,y:-0.3,$SlideOut:true,$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,y:-0.3,$During:{$Top:[0.3,0.7]},$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,y:0.3,$SlideOut:true,$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:0.3,$Cols:2,$During:{$Left:[0.3,0.7]},$ChessMode:{$Column:3},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:0.3,$Cols:2,$SlideOut:true,$ChessMode:{$Column:3},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,y:0.3,$Rows:2,$During:{$Top:[0.3,0.7]},$ChessMode:{$Row:12},$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,y:0.3,$Rows:2,$SlideOut:true,$ChessMode:{$Row:12},$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,y:0.3,$Cols:2,$During:{$Top:[0.3,0.7]},$ChessMode:{$Column:12},$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,y:-0.3,$Cols:2,$SlideOut:true,$ChessMode:{$Column:12},$Easing:{$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:0.3,$Rows:2,$During:{$Left:[0.3,0.7]},$ChessMode:{$Row:3},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:-0.3,$Rows:2,$SlideOut:true,$ChessMode:{$Row:3},$Easing:{$Left:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:0.3,y:0.3,$Cols:2,$Rows:2,$During:{$Left:[0.3,0.7],$Top:[0.3,0.7]},$ChessMode:{$Column:3,$Row:12},$Easing:{$Left:$Jease$.$InCubic,$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,x:0.3,y:0.3,$Cols:2,$Rows:2,$During:{$Left:[0.3,0.7],$Top:[0.3,0.7]},$SlideOut:true,$ChessMode:{$Column:3,$Row:12},$Easing:{$Left:$Jease$.$InCubic,$Top:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,$Delay:20,$Clip:3,$Assembly:260,$Easing:{$Clip:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,$Delay:20,$Clip:3,$SlideOut:true,$Assembly:260,$Easing:{$Clip:$Jease$.$OutCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,$Delay:20,$Clip:12,$Assembly:260,$Easing:{$Clip:$Jease$.$InCubic,$Opacity:$Jease$.$Linear},$Opacity:2},
              {$Duration:1200,$Delay:20,$Clip:12,$SlideOut:true,$Assembly:260,$Easing:{$Clip:$Jease$.$OutCubic,$Opacity:$Jease$.$Linear},$Opacity:2}
            ];
            
            var jssor_1_options = {
              $AutoPlay: true,
              $SlideshowOptions: {
                $Class: $JssorSlideshowRunner$,
                $Transitions: jssor_1_SlideshowTransitions,
                $TransitionsOrder: 1
              },
              $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$
              },
              $ThumbnailNavigatorOptions: {
                $Class: $JssorThumbnailNavigator$,
                $Cols: 10,
                $SpacingX: 8,
                $SpacingY: 8,
                $Align: 360
              }
            };
            
            var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);
            
            //responsive code begin
            //you can remove responsive code if you don't want the slider scales while window resizing
            function ScaleSlider() {
                var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
                if (refSize) {
                    refSize = Math.min(refSize, 800);
                    jssor_1_slider.$ScaleWidth(refSize);
                }
                else {
                    window.setTimeout(ScaleSlider, 30);
                }
            }
            ScaleSlider();
            $(window).bind("load", ScaleSlider);
            $(window).bind("resize", ScaleSlider);
            $(window).bind("orientationchange", ScaleSlider);
            //responsive code end
        });
</script>