<div id="row">
	<div class="12u 12u(mobile)">
		<ol class="breadcrumb">
			<li><a href="<?php echo url(); ?>"><i class="fa fa-home"></i> Home</a></li>
			<li class="active">成果展示</li>
		</ol>
	</div>
	<div id="content">
		<article style="min-height:400px;" class="box post">
			<header><h2><i class="fa fa-gavel">&nbsp;</i><strong>修繕作品</strong> </h2></header>
			<?php 
				if(is_array($data)) {
					$num = count($data);
					foreach($data as $k0 => $v0) {
						if(is_file(PATH_FILES._CLASS.'/'.$v0['product_id'].'/'.$v0['cover'])) image_reformat(PATH_FILES._CLASS.'/'.$v0['product_id'].'/'.$v0['cover'], 'jpg', 249, 166);
						if(($k0%4) == 0) {	echo '<div class="row" style="min-height: 280px;">';}		

						echo '<div class="col-lg-3 col-md-3 col-xs-6 col-sm-6">
								<header>'.$v0['name'].'</header>
								<p><a href="'.url('detail', 'index', ['id'=>$v0['product_id']]).'" class="image" style="padding:0.2em;"> <img onerror="this.src=\''.static_file('images/origin.png').'\'" src="'.URL_FILES._CLASS.'/'.$v0['product_id'].'/'.sinechat_Thumbnail($v0['cover'], 249, 166).'" width="249" height="166"></a></p>
							</div>';
						if(($k0%4) == 3 || $k0 == ($num-1)) {	echo '</div>';	}
					}
				}
			?>
			<div class="row" style="min-height:30px;">
				<ul id="pagination-demo" class="pagination-sm"></ul>
			</div>
		</article>
	</div>
</div>

<script>
	$('#pagination-demo').twbsPagination({
		totalPages: 8,
		visiblePages: 5,
		first:'第一頁',
		prev :'上一頁',
		next  :'下一頁',
		last  :'最後一頁',
		// href: '?page={{number}}',
		onPageClick: function (event, page) {
			$('#page-content').text('Page ' + page);
		}
	});
</script>
