<section class="content-header">
	<div class="box-body"><h2>新誠聯絡資訊</h2></div>
	<ol class="breadcrumb">
		<li><a href="<?php echo url('admin', 'index') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">新誠聯絡資訊</li>
	</ol>
</section>
<section class="content">
	<div class="box">
		<div class="box-body">
			<table class="table table-bordered">
				<tr>
					<th style="width:20%">名稱</th>
					<th style="width:40%">內容</th>
					<th style="width:20%">顯示狀態</th>
					<th style="width:20%">修改時間</th>
				</tr>
				<?php 
					foreach($data as $k0 => $v0) {
						echo '<tr class="data">
								<td>'.$v0['name'].'</td>
								<td><div class="input-group">
										<div class="input-group-addon bg-light-blue color-palette">
											<i class="fa '.$a_icon[$v0['name']].'"></i>
										</div>
										<input type="text" name="value" class="form-control" value="'.$v0['value'].'">
									</div>
								</td>
								<td>
									<div class="form-group">
										<label for="r'.$v0['info_id'].'_1">
											<input id="r'.$v0['info_id'].'_1" type="radio" name="status" class="minimal-red" value="open" >
											Open
										</label>&nbsp;&nbsp;&nbsp;
										<label for="r'.$v0['info_id'].'_2">
											<input id="r'.$v0['info_id'].'_2" type="radio" name="status" class="minimal-red" value="close">
											Close
										</label>
									</div>
								</td>
								<td>'.$v0['modify_time'].'</td>
							</tr>';
					}
				?>
			</table>
		</div>
		<div class="box-footer">
			
		</div>
	</div>
</section>

<script>

$(function () {
  	//Red color scheme for iCheck
    $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
      checkboxClass: 'icheckbox_minimal-red',
      radioClass: 'iradio_minimal-red'
    });


	$('#save').on('click', function(){
		var data = new Array();
		$('tr.data').each(function (k, v){
			var obj = $(v);
			var tmp = [
				$(obj).find(':input[name="url"]').val(),
				$(obj).find('[name="sort"] option:selected').val(),
				$(obj).find('div[id^="switch_"]').attr('class'),
			];
			data.push(tmp);
		});
	
		$.post('<?php echo ajax_url(URL_ADMIN2_AJAX, P_CLASS, P_FUNCTION) ?>' , {
			data : JSON.stringify(data),
		},function(r){
			r = $.parseJSON(r);
			if(r.result == 1) {
				_jbox(r, 'success');
			}else{
				_jbox(r, 'error');			
			}
		});
	});
  
});
</script>
</body>
</html>