<section class="content-header">
	<div class="box-body"><h2>新誠聯絡資訊</h2></div>
	<ol class="breadcrumb">
		<li><a href="<?php echo url('admin', 'index') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">新誠聯絡資訊</li>
	</ol>
</section>
<section class="content">
	<div class="box">
		<div class="box-body">
			<table class="table table-bordered">
				<tr>
					<th style="width:20%">名稱</th>
					<th style="width:40%">內容</th>
					<th style="width:20%">顯示狀態</th>
					<th style="width:20%">修改時間</th>
				</tr>
				<?php 
					foreach($data as $k0 => $v0) {
						if($v0['status'] == 'open') {
							$o_checked ='checked';$c_checked='null';}else{$c_checked='checked';$o_checked='null';}
						echo '<tr class="data" data-info_id="'.$v0['info_id'].'">
								<td class="text-light-blue"><h4>'.ucfirst($v0['name']).'</h4></td>
								<td><div class="input-group">
							            <span class="input-group-addon"><i style="font-size:20px;" class="fa '.$a_icon[$v0['name']].'"></i></span>
										<input type="text" name="value" class="form-control" value="'.$v0['value'].'">
									</div>
								</td>
								<td>
									<div class="form-group">
										<label for="r'.$v0['info_id'].'_1">
											<input id="r'.$v0['info_id'].'_1" type="radio" name="radio_'.$v0['info_id'].'" class="minimal-red" value="open" '.$o_checked.'>
											Open
										</label>&nbsp;&nbsp;&nbsp;
										<label for="r'.$v0['info_id'].'_2">
											<input id="r'.$v0['info_id'].'_2" type="radio" name="radio_'.$v0['info_id'].'" class="minimal-red" value="close" '.$c_checked.'>
											Close
										</label>
									</div>
								</td>
								<td>'.$v0['modifytime'].'</td>
							</tr>';
					}
				?>
			</table>
		</div>
		<div class="box-footer">
		</div>
	</div>
</section>
<a class="btn btn-app" id="save">
	<i class="fa fa-save"></i> 儲存(Save)
</a>

<script>
$(function () {
	$('#save').on('click', function(){
		var data = new Array();
		$('tr.data').each(function(){
			var tmp, id = $(this).data('info_id');
			tmp = {'id':id, 'value':$(this).find('input[name="value"]').val(), 'status':$(this).find('input[name="radio_'+id+'"]:checked').val()};
			data.push(tmp);
		});

		$.post('<?php echo url('admin', 'info/edit') ?>' , {
			act :'info',
			data : JSON.stringify(data),
		},function(r){
			r = $.parseJSON(r);
			if(r.result == 1) {
				_jbox(r, 'success');
			}else{
				_jbox(r, 'error');			
			}
		});
	
	});
  
});
</script>
</body>
</html>