<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>AdminLTE 2 | Log in</title>
	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<?php set_css('css/bootstrap.min.css'); ?>
	<?php set_css('css/font-awesome.min.css'); ?>
	<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
	<?php set_css('css/adminlte/AdminLTE.min.css'); ?>
	<?php set_css('js/icheck/square/blue.css'); ?>
	<?php set_css('js/jBox/jBox.css'); ?>
	<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body class="hold-transition login-page">
<div class="login-box">
	<div class="login-logo">
		<a href="<?php echo url() ?>"><b>Sinechat</b> admin</a>
	</div>
	<div class="login-box-body">
		<div class="form-group has-feedback">
			<input type="email" class="form-control" placeholder="Email">
			<span class="glyphicon glyphicon-envelope form-control-feedback"></span>
		</div>
		<div class="form-group has-feedback">
			<input type="password" class="form-control" placeholder="Password">
			<span class="glyphicon glyphicon-lock form-control-feedback"></span>
		</div>
		<div class="row">
			<div class="col-xs-4">
				<button type="submit" class="btn btn-primary btn-block btn-flat" onclick="login_check()">Sign In</button>
			</div>
		</div>
	</div>
</div>
<script src="<?php echo URL_JS.'jquery.min.js' ?>"></script>
<?php set_js('js/bootstrap-admin/js/bootstrap.min.js'); ?>
<?php set_js('js/icheck/icheck.min.js'); ?>
<?php set_js('js/jBox/jBox.js'); ?>
<script>
	function login_check() {
		$.post('<?php echo url('/admin', 'login') ?>', {
		
		
		},function(r){
			r = $.parseJSON(r);
			var box = new jBox('Modal', {
				closeButton: 'title',
				delayOpen: 300,
				maxWidth: 600,
				minWidth: 120,
				title: '<span style="display: inline-block;height: 100%;vertical-align: middle;"><i style="color:#DD4B39;" class="fa fa-times-circle"></span>',
				onCloseComplete: function() {
					
				},
			}).setContent('<div style="color: #757575; font-size: 16px;line-height: 30px;font-weight:500">' + r.message + '</div>').open();
		});
	
	}

	$(function () {
		$('input').iCheck({
			checkboxClass: 'icheckbox_square-blue',
			radioClass: 'iradio_square-blue',
			increaseArea: '20%' // optional
		});
	});
</script>
</body>
</html>
