<div id="banner-wrapper">
	<div class="inner">
		<a href="<?php echo url('index', 'index') ?>" class="image"><img src="<?php echo URL_IMG.'12.jpg' ?>" style="max-width:980px;max-height:490px;"></a>
	</div>
	<div class="inner">
		<a href="<?php echo url('index', 'index') ?>" class="image"><img src="<?php echo URL_IMG.'11.jpg' ?>" style="max-width:980px;max-height:490px;"></a>
	</div>
	<div class="inner">
		<a href="<?php echo url('index', 'index') ?>" class="image"><img src="<?php echo URL_IMG.'14.jpg' ?>" style="max-width:980px;max-height:490px;" ></a>
	</div>
</div>
