<?php 
	$query = query_despace('select * from `setbanner` where `setbanner_id` = 1 limit 1 ;');
	$result = mysql_query($query);
	$a_banner = array();
	while($row = mysql_fetch_assoc($result)){ $banner = $row;	}
	if(mysql_num_rows($result) > 0) $a_banner = explode(',',  $banner['image']);

?>
<div id="banner-wrapper">
	<?php 
		foreach ($a_banner as $k0 => $v0) {
			if(is_file(PATH_FILES.'setbanner/'.$v0)) image_reformat(PATH_FILES.'setbanner/'.$v0, 'jpg', 980, 490);
			echo '<div class="inner"><a href="'.url('index', 'index').'" class="image"><img src="'.URL_FILES.'setbanner/'.$v0.'" style="max-width:980px;max-height:490px;"></a></div>';
		}
	?>
</div>