<!--[if lte IE 8]><script src="assets/js/ie/html5shiv.js"></script><![endif]-->
<!--[if lte IE 8]><link rel="stylesheet" href="assets/css/ie8.css" /><![endif]-->
<?php 
	set_css('js/owl.carousel/css/owl.carousel.css');
	set_css('js/owl.carousel/css/owl.theme.css');
	set_css('js/owl.carousel/css/owl.transitions.css');
?>

<!-- Scripts -->
<script src="<?php echo URL_JS.'jquery.min.js' ?>"></script>
<script src="<?php echo URL_JS.'skel.min.js' ?>"></script>
<script src="<?php echo URL_JS.'skel-viewport.min.js' ?>"></script>
<script src="<?php echo URL_JS.'main.js' ?>"></script>
<script src="<?php echo URL_JS.'jquery.dropotron.min.js' ?>"></script>
<script src="<?php echo URL_JS.'util.js' ?>"></script>
<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
<?php 
	set_js('js/owl.carousel/js/owl.carousel.min.js');
?>


<?php 
/**
 * 不同分類引入各自的css/js file
 */
switch(_CLASS) {
	case 'about':
		set_css('js/bootsrap-custom/css/bootstrap.min.css');
		set_css('js/bootsrap-custom/js/bootstrap.min.js');
	break;
	case 'detail':
		set_css('js/bootsrap-custom/css/bootstrap.min.css');
		set_css('css/style.css');
		set_css('js/bootsrap-custom/js/bootstrap.min.js');
		set_css('js/jssor.slider/css/jssor.slider.css');
		set_js('js/jquery.twbsPagination.min.js');
		set_js('js/jssor.slider/js/jssor.slider.min.js');
	break;
	case 'index':
		set_css('js/jBox/jBox.css');
		set_js('js/jBox/jBox.js');
	break;
	case 'service':
		set_css('js/smartmenus/css/sm-core-css.css');
		set_css('js/smartmenus/css/sm-mint/sm-mint.css');
		set_js('js/smartmenus/js/jquery.smartmenus.min.js');
		set_css('js/bootsrap-custom/css/bootstrap.min.css');
		set_css('js/bootsrap-custom/js/bootstrap.min.js');
	break;
	case 'product':
		set_css('js/bootsrap-custom/css/bootstrap.min.css');
		set_css('css/style.css');
		set_css('js/bootsrap-custom/js/bootstrap.min.js');
		set_css('js/jssor.slider/css/jssor.slider.css');
		set_js('js/jquery.twbsPagination.min.js');
		set_js('js/jssor.slider/js/jssor.slider.min.js');
	break;
	
	case 'contact':
		set_css('js/bootsrap-custom/css/bootstrap.min.css');
		set_css('js/bootsrap-custom/js/bootstrap.min.js');

	break;	
}
	set_css('css/main.css');
	set_css('css/font-awesome/css/font-awesome.css');

?>

