<div id="header-wrapper">
	<div id="header" class="container">

		<!-- Logo -->
			<h1 id="logo" class="header_line" style="text-align:left;"><a href="index.html">新誠居家修繕工程</a></h1>
			<div class="line"></div>
		<!-- Nav -->
			<nav id="nav">
				<ul style="height:36px;">
					<li><a class="" href="<?php echo url('about', 'index') ?>"><span <?php echo (_CLASS=='about') ? 'class="active"' : null ; ?>>關於新誠</span></a></li>
					<li>
						<a href="<?php echo url('service', 'index') ?>" class=""><span>修繕項目</span></a>
						<ul>
							<li><a href="javascript:void(0)">Lorem ipsum dolor</a></li>
							<li><a href="javascript:void(0)">Magna phasellus</a></li>
							<li><a href="javascript:void(0)">Etiam dolore nisl</a></li>
							<li>
								<a href="javascript:void(0)">Phasellus consequat</a>
								<ul>
									<li><a href="javascript:void(0)">Magna phasellus</a></li>
									<li><a href="javascript:void(0)">Etiam dolore nisl</a></li>
									<li><a href="javascript:void(0)">Phasellus consequat</a></li>
								</ul>
							</li>
							<li><a href="javascript:void(0)">Veroeros feugiat</a></li>
						</ul>
					</li>
					<li><a class="" href="<?php echo url('product', 'index') ?>"><span>修繕作品</span></a></li>
					<li><a class="" href="<?php echo url('contact', 'index') ?>"><span>聯絡我們</span></a></li>
					<li><a class="" href="<?php echo url('index', 'index') ?>"><span>回首頁</span></a></li>
				</ul>
			</nav>

	</div>
</div>	