<div id="header-wrapper">
	<div id="header" class="container">
		<h1 id="logo" class="header_line" style="text-align:left;"><a href="<?php echo url('index', 'index') ?>">新誠修繕工程</a></h1>
		<h5 class="header_sub" style="text-align:left;">Sinechat Refurbishment</h5>
		<div class="line" style="margin-left:0;"></div>
		<nav id="nav">
			<ul style="height:36px;">
				<li>
					<a href="<?php echo url('index', 'index') ?>"><span>回首頁</span></a>
				</li>
				<li>
					<a href="<?php echo url('about', 'index') ?>"><span <?php echo (_CLASS=='about') ? 'class="active"' : null ; ?>>關於新誠</span></a>
				</li>
				<li>
					<a href="<?php echo url('service', 'index') ?>"><span <?php echo (_CLASS=='service') ? 'class="active"' : null ; ?>>修繕項目</span></a>
				</li>
				<li>
					<a href="<?php echo url('product', 'index') ?>"><span <?php echo (_CLASS=='product') ? 'class="active"' : null ; ?>>成果展示</span></a>
				</li>
				<li>
					<a href="<?php echo url('contact', 'index') ?>"><span <?php echo (_CLASS=='contact') ? 'class="active"' : null ; ?>>聯絡我們</span></a>
				</li>
			</ul>
		</nav>
	</div>
</div>
