<div class="row">
	<div class="12u 12u(mobile) important(mobile)">
		<ol class="breadcrumb">
			<li><a href="<?php echo url(); ?>"><i class="fa fa-home"></i> Home</a></li>
			<li class="active">修繕項目</li>
		</ol>
	</div>
	<div id="content" class="3u 12u(mobile) service">
		<article class="box post">
			<header><h2><i class="fa fa-gavel">&nbsp;</i><strong>修繕項目</strong> </h2></header>
			<nav id="main-nav" role="navigation">
				<ul id="main-menu-service" class="sm sm-vertical sm-mint">
					<?php 
						foreach($a_service as $k0 => $v0) {
							echo '<li>';
								if(isset($v0['service'])) {
									if(count($v0['service']) > 1) {
										echo '<a href="javascript:void(0)">'.$v0['servicearea_name'].'</a><ul>';
										foreach($v0['service'] as $k1 => $v1) {
											echo '<li><a id="content_'.$v1['service_id'].'" href="javascript:void(0)">'.$v1['name'].'</a></li>';
										}
										echo '</ul>';
									}else{
										echo '<a id="content_'.$v0['service'][0]['service_id'].'" href="javascript:void(0)">'.$v0['servicearea_name'].'</a>';	
									}
								}
							echo '</li>';
						}
					?>
				</ul>
			</nav>
		</article>
	</div>
	<div id="sidebar" class="9u 12u(mobile) service editor_content">
		<?php 
			foreach($a_content as $k0 => $v0) {
				echo '<section class="content_'.$v0['service_id'].'">
					<ul class="divided">
						<li>
							<article>'.htmlspecialchars_decode($v0['content']).'</article>
						</li>
					</ul>
				</section>';
			}
		?>
	</div>
</div>

<script>
	$(function() {
		$('section').hide(); 

		$('#main-menu-service').find('a[id]').on('click', function(){
			$('section').hide();
			var target = $(this).attr('id');
			$('section.'+target).show();
		});
		$('#main-menu-service').find('a[id^="content_"]:first').click();
		$('#main-menu-service').smartmenus({
			mainMenuSubOffsetX: 6,
			mainMenuSubOffsetY: -8,
			subMenusSubOffsetX: 6,
			subMenusSubOffsetY: -8
		});
		
		$('.editor_content').find('img').each(function(k,v){
			var h_w = $(this).css(['height', 'width']);
			$(this).removeAttr('style').css('max-height', h_w.height).css('max-width', h_w.width);
			$(this).wrap('<span class="image"></div>'); 
		});	
		$('td').css('vertical-align', 'top');
	});
</script>