<section class="content-header">
	<div class="box-body"><h2>修繕項目分類</h2></div>
	<h1>				
		<small><p class="text-light-blue"></p></small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="<?php echo url('admin', 'index') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
		<li><a href="<?php echo url('admin', 'servicearea') ?>">修繕項目分類</a></li>
		<li class="active">詳情</li>
	</ol>
</section>
<section class="content">
	<div class="box">
		<div class="box-body">
			<div class="row">
				<div class="col-md-10">
					<div class="box-body box-solid">
						<div class="box-header with-border">
							<i class="fa fa-file-text-o"></i>
							<h3 class="box-title"> <?php echo ($act == 'add') ? '新增修繕項目分類' : '編輯分類 ： '.$data['name'] ?> </h3>
						</div>
						<div class="box-body">
							<dl class="dl-horizontal">
								<dt>編號:</dt>
									<dd># <?php echo $data['servicearea_id'] ?></dd>
								<br>
								<dt>標題:</dt>
									<dd>
										<input type="text" class="form-control" name="name" placeholder="分類名稱" style="width:50%" value="<?php echo $data['name'] ?>">
									</dd>
								<br>
								<dt>狀態:</dt>
									<dd>
										<div class="form-group">
											<label for="r1">
												<input id="r1" type="radio" name="status" class="minimal-red" value="open" <?php if($data['status'] == 'open') echo 'checked'; ?>>
												Open
											</label>&nbsp;&nbsp;&nbsp;
											<label for="r2">
												<input id="r2" type="radio" name="status" class="minimal-red" value="close" <?php if($data['status'] == 'close') echo 'checked'; ?>>
												Close
											</label>
										</div>
									</dd>
								<br>
								<?php if(!empty($data['modify_time'])) echo '<dt>最後修改時間:</dt><dd>'.$data['modify_time'].'</dd><br> '; ?> 
							</dl>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<a class="btn btn-app" href="<?php echo url('admin', 'servicearea') ?>">
	<i class="fa fa-angle-double-left"></i> 上一頁
</a>

<a class="btn btn-app " id="save">
	<i class="fa fa-save"></i> 儲存(Save)
</a>

<?php 
	if($act =='edit') echo '<a class="btn btn-app" id="delete"><i class="fa fa-trash-o"></i> 刪除(Delete)</a>';
?>
<script>

$(function () {
  	//Red color scheme for iCheck
    $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
      checkboxClass: 'icheckbox_minimal-red',
      radioClass: 'iradio_minimal-red'
    });
	
	$('#save').on('click', function(){
		$.post('<?php echo url('admin', 'servicearea/edit') ?>' , {
			act : '<?php echo $act ?>',
			servicearea_id : '<?php echo $data['servicearea_id'] ?>',
			name : $('input[name="name"]').val(),
			status : $('input[name="status"]:checked').val(),
		},function(r){
			r = $.parseJSON(r);
			if(r.result == 1) {
				_jbox(r, 'success');
			}else{
				_jbox(r, 'error');			
			}
		});
		
	});

	$('#delete').on('click', function(){
		var Confirm_box = new jBox('Confirm', {
				cancelButton: '否',
				confirmButton: '是',
				title : '<span style="display: inline-block;height: 100%;vertical-align: middle;"><i style="color:#3C8DBC;font-size:2em ;" class="fa fa-info-circle"></span>',
				confirm: function() {
					$.post('<?php echo url('admin', 'servicearea/delete') ?>' , {
						servicearea_id : '<?php echo $data['servicearea_id'] ?>',
					},function(r){
						r = $.parseJSON(r);
						if(r.result == 1) {
							_jbox(r, 'success');
						}else{
							_jbox(r, 'error');			
						}
					});
				},
				onCloseComplete: function() {	
					Confirm_box.destroy();
				}
			}).setContent(
				'<div>' +
				'<p>確定要刪除此筆資料嗎?</p>' +
				'</div>'
			).open();
	});
	
});

</script>