<section class="content-header">
	<div class="box-body"><h2>修繕項目介紹</h2></div>
	<h1>				
		<small><p class="text-light-blue"></p></small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="<?php echo url('admin', 'index') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">修繕項目介紹</li>
	</ol>
</section>
<section class="content">
	<div class="box">
		<div class="box-body">
			<div class="row">
				<div class="col-md-12">
					<div class="box-body">
						<table id="example1" class="table table-bordered table-striped display" width="100%">
							<thead>
								<tr>
									<th>#</th>
									<th>編輯</th>
									<th>名稱</th>
									<th>分類群組</th>
									<th>排序</th>
									<th>修改時間</th>
									<th>狀態</th>
								</tr>
							</thead>
							<tbody>
								<?php 
								foreach($data as $k0 => $v0) {
								$status = ($v0['status']== 'open') ? '<span class="label label-success">OPEN</span>' : '<span class="label label-warning">CLOSE</span>';
									echo '<tr>
											<td>'.$v0['service_id'].' </td>
											<td><a href="'.url('admin', 'service/edit', ['service_id'=>$v0['service_id']]).'">編輯</a></td>
											<td><a href="'.url('admin', 'service/edit', ['service_id'=>$v0['service_id']]).'">'.$v0['name'].'</a></td>
											<td>'.$v0['servicearea_id'].' - '.$v0['servicearea_name'].'</td>
											<td>'.$v0['seqence'].'</td>
											<td>'.$v0['modifytime'].' </td>
											<td>'.$status.' </td>																
										</tr>';
								}
								?>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
		<a class="btn btn-app" href="<?php echo url('admin', 'service/edit'); ?>">
			<i class="fa fa-pencil"></i> 新增
		</a>
</section>
<script>
$(function () {
	var table = $("#example1").DataTable({
		"order": [[ 0, "asc" ]],
	});
	
	if($(window).width()<1024){
        var column = table.column( 5 );
        column.visible( ! column.visible() );
	}
	if($(window).width()<900){
        var column = table.column( 4 );
        column.visible( ! column.visible() );
	}
	if($(window).width()<440){
        var column = table.column( 3 );
        column.visible( ! column.visible() );
        var column2 = table.column( 6 );
        column2.visible( ! column2.visible() );
	}
});

</script>