<section class="content-header">
	<div class="box-body"><h2>作品內容</h2></div>
	<h1>				
		<small><p class="text-light-blue"></p></small>
	</h1>
	<ol class="breadcrumb">
		<li><a href="<?php echo url('admin', 'index') ?>"><i class="fa fa-dashboard"></i> Home</a></li>
		<li><a href="<?php echo url('admin', 'servicearea') ?>">作品內容</a></li>
		<li class="active">詳情</li>
	</ol>
</section>
<section class="content">
	<div class="box">
		<div class="box-body">
			<div class="row">
				<div class="col-md-10">
					<div class="box-body box-solid">
						<div class="box-header with-border">
							<i class="fa fa-file-text-o"></i>
							<h3 class="box-title"> <?php echo ($act == 'add') ? '新增作品' : '編輯作品 ： '.$data['name'] ?> </h3>
						</div>
						<div class="box-body">
							<dl class="dl-horizontal">
								<dt>編號:</dt>
									<dd># <?php echo $data['product_id'] ?></dd>
								<br>
								<dt>名稱:</dt>
									<dd>
										<input type="text" class="form-control" name="name" placeholder="作品名稱" style="width:30%" value="<?php echo $data['name'] ?>">
									</dd>
								<br>
								<dt>作品修繕項目:</dt>
									<dd>
										<select class="form-control" id="servicearea" style="width:30%">
											<option value="">選擇一個項目</option>
											<?php 
												foreach($servicearea as $k0 => $v0) {
													echo ($v0['service_id'] == $data['service_id']) ?
													'<option value="'.$v0['service_id'].'" selected="selected">'.$v0['service_id'].' - '.$v0['name'].'</option>' :
													'<option value="'.$v0['service_id'].'">'.$v0['service_id'].' - '.$v0['name'].'</option>';
												}
											?>
										</select>
									</dd>
								<br>
								<dt>排序:</dt>
									<dd>
										<input type="number" class="form-control" name="seqence" placeholder="1~255" min="0" max="255" style="width:20%" value="<?php echo $data['seqence'] ?>">
									</dd>
								<br>
								<dt>狀態:</dt>
									<dd>
										<div class="form-group">
											<label for="r1">
												<input id="r1" type="radio" name="status" class="minimal-red" value="open" <?php if($data['status'] == 'open') echo 'checked'; ?>>
												Open
											</label>&nbsp;&nbsp;&nbsp;
											<label for="r2">
												<input id="r2" type="radio" name="status" class="minimal-red" value="close" <?php if($data['status'] == 'close') echo 'checked'; ?>>
												Close
											</label>
										</div>
									</dd>
								<br>
								<dt>內文:</dt>
									<dd>
										<div class="form-group">
											<form method="post">
												<textarea rows="10" cols="50" id="content" name="content" class="ckeditor"><?php echo $data['content'] ?></textarea>
												<script type="text/javascript">CKEDITOR.replace('content',
												{toolbar : 'Full'});
												</script><br>
											</form>
										</div>
									</dd>
								<br>
								<dt>相片:</dt>
									<dd>
										<div class="form-group">
										    <form id="fileupload" action="//jquery-file-upload.appspot.com/" method="POST" enctype="multipart/form-data">
										        <!-- Redirect browsers with JavaScript disabled to the origin page -->
										        <noscript><input type="hidden" name="redirect" value="https://blueimp.github.io/jQuery-File-Upload/"></noscript>
										        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
										        <div class="row fileupload-buttonbar">
										            <div class="col-lg-7">
										                <!-- The fileinput-button span is used to style the file input field as button -->
										                <span class="btn btn-success fileinput-button">
										                    <i class="glyphicon glyphicon-plus"></i>
										                    <span>Add files...</span>
										                    <input type="file" name="files[]" multiple>
										                </span>
										                <button type="submit" class="btn btn-primary start">
										                    <i class="glyphicon glyphicon-upload"></i>
										                    <span>Start upload</span>
										                </button>
										                <button type="reset" class="btn btn-warning cancel">
										                    <i class="glyphicon glyphicon-ban-circle"></i>
										                    <span>Cancel upload</span>
										                </button>
										                <button type="button" class="btn btn-danger delete">
										                    <i class="glyphicon glyphicon-trash"></i>
										                    <span>Delete</span>
										                </button>
										                <input type="checkbox" class="toggle">
										                <!-- The global file processing state -->
										                <span class="fileupload-process"></span>
										            </div>
										            <!-- The global progress state -->
										            <div class="col-lg-5 fileupload-progress fade">
										                <!-- The global progress bar -->
										                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
										                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
										                </div>
										                <!-- The extended global progress state -->
										                <div class="progress-extended">&nbsp;</div>
										            </div>
										        </div>
										        <!-- The table listing the files available for upload/download -->
										        <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
										    </form>
										</div>
									</dd>
								<br>
								<?php if(!empty($data['modify_time'])) echo '<dt>最後修改時間:</dt><dd>'.$data['modify_time'].'</dd><br> '; ?> 
							</dl>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<a class="btn btn-app" href="<?php echo url('admin', 'service') ?>">
	<i class="fa fa-angle-double-left"></i> 上一頁
</a>

<a class="btn btn-app" id="save">
	<i class="fa fa-save"></i> 儲存(Save)
</a>

<?php 
	if($act =='edit') echo '<a class="btn btn-app" id="delete"><i class="fa fa-trash-o"></i> 刪除(Delete)</a>';
?>
<script>

$(function () {
  	//Red color scheme for iCheck
    $('input[type="checkbox"].minimal-red, input[type="radio"].minimal-red').iCheck({
      checkboxClass: 'icheckbox_minimal-red',
      radioClass: 'iradio_minimal-red'
    });
	
	$('#save').on('click', function(){
		var seqence = $('input[name=seqence]');

		if (!/^\d+$/.test(seqence.val())) {
			seqence.val(/^\d+/.exec(seqence.val()));
			r = {'message': '排序須輸入正整數。'};
			site_jBox(r, 'error');
		}else{
			$.post('<?php echo url('admin', 'service/edit') ?>' , {
				act : '<?php echo $act ?>',
				service_id : '<?php echo $data['service_id'] ?>',
				content : CKEDITOR.instances['content'].getData(),
				name : $('input[name="name"]').val(),
				service_id : $('#servicearea').val(),
				seqence : seqence.val(),
				status : $('input[name="status"]:checked').val(),
			},function(r){
				r = $.parseJSON(r);
				if(r.result == 1) {
					_jbox(r, 'success');
				}else{
					_jbox(r, 'error');			
				}
			});
		}
	});

	$('#delete').on('click', function(){
		var Confirm_box = new jBox('Confirm', {
				cancelButton: '否',
				confirmButton: '是',
				title : '<span style="display: inline-block;height: 100%;vertical-align: middle;"><i style="color:#3C8DBC;font-size:2em ;" class="fa fa-info-circle"></span>',
				confirm: function() {
					$.post('<?php echo url('admin', 'service/delete') ?>' , {
						service_id : '<?php echo $data['service_id'] ?>',
					},function(r){
						r = $.parseJSON(r);
						if(r.result == 1) {
							_jbox(r, 'success');
						}else{
							_jbox(r, 'error');			
						}
					});
				},
				onCloseComplete: function() {	
					Confirm_box.destroy();
				}
			}).setContent(
				'<div>' +
				'<p>確定要刪除此筆資料嗎?</p>' +
				'</div>'
			).open();
	});
	
});

</script>

<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
                <button class="btn btn-primary start" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start</span>
                </button>
            {% } %}
            {% if (!i) { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                    <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                    <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
                <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
                <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
        </td>
    </tr>
{% } %}
</script>